### ISSUE TITLE
1.3.5 segmentation fault internet_address_list_parse_string

### ISSUE THREAD

**Issue by Safari77** [vstakhov/rspamd#1025]
This is your debian package.

```
Oct 12 02:01:23 whatever kernel: rspamd[11765]: segfault at 1000000001 ip 00007fe596070a9a sp 00007fff276b6be0 error 4 in libglib-2.0.so.0.4800.1[7fe59600a000+10f000]
Oct 12 02:01:23 whatever rspamd[11455]: (main) <e0f219>; main; rspamd_cld_handler: normal process 11765 terminated abnormally by signal: 11 and created core file
```

```
Program received signal SIGSEGV, Segmentation fault.
0x00007fe596070a9a in g_slice_alloc () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) bt
#0  0x00007fe596070a9a in g_slice_alloc () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007fe595708a03 in ?? () from /usr/lib/x86_64-linux-gnu/libgmime-2.6.so.0
#2  0x00007fe59572d539 in ?? () from /usr/lib/x86_64-linux-gnu/libgmime-2.6.so.0
#3  0x00007fe5954d1317 in g_type_create_instance () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007fe5954b331b in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007fe5954b4c01 in g_object_newv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007fe59572e157 in ?? () from /usr/lib/x86_64-linux-gnu/libgmime-2.6.so.0
#7  0x00007fe59572e8f6 in ?? () from /usr/lib/x86_64-linux-gnu/libgmime-2.6.so.0
#8  0x00007fe59572f972 in internet_address_list_parse_string () from /usr/lib/x86_64-linux-gnu/libgmime-2.6.so.0
#9  0x00007fe5957142b3 in ?? () from /usr/lib/x86_64-linux-gnu/libgmime-2.6.so.0
#10 0x00007fe59571442b in ?? () from /usr/lib/x86_64-linux-gnu/libgmime-2.6.so.0
#11 0x00007fe59571e620 in g_mime_parser_construct_message () from /usr/lib/x86_64-linux-gnu/libgmime-2.6.so.0
#12 0x00000000004d7f79 in rspamd_message_parse (task=task@entry=0x7fe58837e260) at /rspamd-1.3.5/src/libmime/message.c:1449
#13 0x00000000004c345f in rspamd_task_process (task=task@entry=0x7fe58837e260, stages=stages@entry=16383) at /rspamd-1.3.5/src/libserver/task.c:579
#14 0x00000000004c3369 in rspamd_task_process (task=task@entry=0x7fe58837e260, stages=stages@entry=16383) at /rspamd-1.3.5/src/libserver/task.c:688
#15 0x00000000004c3369 in rspamd_task_process (task=task@entry=0x7fe58837e260, stages=stages@entry=16383) at /rspamd-1.3.5/src/libserver/task.c:688
#16 0x0000000000448691 in rspamd_worker_body_handler (conn=<optimized out>, msg=<optimized out>, 
    chunk=0x7fe5914bab10 "Received: from whatever (host-109-204-147-154.tp-fne.tampereenpuhelin.net [109.204.147.154]) by localhost (Postfix) with ESMTP id 81dadd9fa7;\r\nReceived: (qmail 4795 invoked by uid 500); 11 Oct 2016 22"..., len=739) at /rspamd-1.3.5/src/worker.c:213
#17 0x000000000046c731 in rspamd_http_on_message_complete (parser=<optimized out>) at /rspamd-1.3.5/src/libutil/http.c:895
#18 0x00000000008f2396 in http_parser_execute (parser=parser@entry=0x7fe58837d1d0, settings=settings@entry=0x7fe58837d1f0, data=<optimized out>, 
    len=len@entry=739) at /rspamd-1.3.5/contrib/http-parser/http_parser.c:1772
#19 0x000000000046df01 in rspamd_http_event_handler (fd=<optimized out>, what=<optimized out>, ud=0x7fe591424e30)
    at /rspamd-1.3.5/src/libutil/http.c:1121
#20 0x00007fe595265a0c in event_process_active_single_queue (activeq=0x7fe5917ee7f0, base=0x7fe591410980) at event.c:1350
#21 event_process_active (base=<optimized out>) at event.c:1420
#22 event_base_loop (base=0x7fe591410980, flags=flags@entry=0) at event.c:1621
#23 0x0000000000448056 in start_worker (worker=0x7fe59174d700) at /rspamd-1.3.5/src/worker.c:564
#24 0x00000000004c8d2d in rspamd_fork_worker (rspamd_main=rspamd_main@entry=0x7fe591466080, cf=cf@entry=0x7fe59159b450, index=index@entry=0, 
    ev_base=ev_base@entry=0x7fe591410980) at /rspamd-1.3.5/src/libserver/worker_util.c:596
#25 0x0000000000445613 in spawn_worker_type (rspamd_main=0x7fe591466080, ev_base=0x7fe591410980, cf=0x7fe59159b450) at /rspamd-1.3.5/src/rspamd.c:514
#26 0x0000000000445bd2 in spawn_workers (rspamd_main=rspamd_main@entry=0x7fe591466080, ev_base=ev_base@entry=0x7fe591410980)
    at /rspamd-1.3.5/src/rspamd.c:596
#27 0x000000000043a4a5 in main (argc=1, argv=0x7fff276b7b98, env=<optimized out>) at /rspamd-1.3.5/src/rspamd.c:1335
```

**Comment by vstakhov** [comment]
It looks like a bug in gmime. Could you please attach a message sample (or send it to my email)?

**Comment by Safari77** [comment]
```
#0  0x00007fe596070a9a in g_slice_alloc () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007fe596027db1 in g_ptr_array_sized_new () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00000000004d8a39 in rspamd_message_get_header_array (task=task@entry=0x7fe588380010, field=0x7fe59142a3a0 "Content-Type", 
    strong=strong@entry=0) at /rspamd-1.3.5/src/libmime/message.c:1803
#3  0x00000000004bbaa3 in rspamd_re_cache_exec_re (is_strong=0, re_class=0x7fe591437720, re=0x7fe5916891b0, rt=0x7fe59141b980, task=0x7fe588380010)
    at /rspamd-1.3.5/src/libserver/re_cache.c:756
#4  rspamd_re_cache_process (task=task@entry=0x7fe588380010, rt=0x7fe59141b980, re=0x7fe5916891b0, type=type@entry=RSPAMD_RE_HEADER, 
    type_data=type_data@entry=0x7fe5916b50e0, datalen=<optimized out>, is_strong=0) at /rspamd-1.3.5/src/libserver/re_cache.c:1082
#5  0x00000000005008cf in rspamd_mime_expr_process_regexp (task=0x7fe588380010, re=0x7fe5916b50b0)
    at /rspamd-1.3.5/src/libmime/mime_expressions.c:808
#6  rspamd_mime_expr_process (input=0x7fe588380010, atom=<optimized out>) at /rspamd-1.3.5/src/libmime/mime_expressions.c:934
#7  0x00000000004f5c5d in rspamd_ast_process_node (expr=expr@entry=0x7fe5916a9b20, flags=flags@entry=0, node=<optimized out>, 
    data=data@entry=0x7fe588380010, track=track@entry=0x0) at /rspamd-1.3.5/src/libutil/expression.c:993
#8  0x00000000004f6b1c in rspamd_process_expression_track (expr=0x7fe5916a9b20, flags=flags@entry=0, data=data@entry=0x7fe588380010, 
    track=track@entry=0x0) at /rspamd-1.3.5/src/libutil/expression.c:1083
#9  0x00000000004f6c17 in rspamd_process_expression (expr=<optimized out>, flags=flags@entry=0, data=data@entry=0x7fe588380010)
    at /rspamd-1.3.5/src/libutil/expression.c:1111
#10 0x00000000004df1a3 in process_regexp_item (task=0x7fe588380010, user_data=0x7fe5916b5090) at /rspamd-1.3.5/src/plugins/regexp.c:409
#11 0x00000000004bfc54 in rspamd_symbols_cache_check_symbol (task=task@entry=0x7fe588380010, item=item@entry=0x7fe59661ed00, 
    total_diff=total_diff@entry=0x7fff276b6f60, pr=pr@entry=0.42058641121998352, checkpoint=0x7fe5883836a0, cache=0x7fe59147b0b0)
    at /rspamd-1.3.5/src/libserver/symbols_cache.c:1210
#12 0x00000000004c1341 in rspamd_symbols_cache_process_symbols (task=task@entry=0x7fe588380010, cache=cache@entry=0x7fe59147b0b0, 
    stage=stage@entry=16) at /rspamd-1.3.5/src/libserver/symbols_cache.c:1575
#13 0x00000000004c1270 in rspamd_symbols_cache_process_symbols (task=task@entry=0x7fe588380010, cache=0x7fe59147b0b0, stage=stage@entry=16)
    at /rspamd-1.3.5/src/libserver/symbols_cache.c:1543
```
