### ISSUE TITLE
Segmentation fault when trying to process directory

### ISSUE THREAD

**Issue by smfreegard** [vstakhov/rspamd#1056]
Running the latest rspamd RPM for CentOS 7 (rspamd-1.4.0-92.git2e2b739.x86_64)

`````
[root@mail1-ewh 2015]# time rspamc --compact -t 60 -n 1024 spam > spam_corpus.log
Segmentation fault (core dumped)

[root@mail1-ewh 2015]# gdb core.8711 
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-80.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
[New LWP 8711]
Reading symbols from /usr/bin/rspamc...Reading symbols from /usr/lib/debug/usr/bin/rspamc.debug...done.
done.
Missing separate debuginfo for 
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/56/a5447ae8db408dd3ae68f0114fae478db03203
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `rspamc --compact -t 60 -n 1024 spam'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007fc66e81b1ca in readdir_r () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install file-libs-5.11-31.el7.x86_64 glib2-2.42.2-5.el7.x86_64 glibc-2.17-106.el7_2.8.x86_64 gmime-2.6.19-1.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.13.2-12.el7_2.x86_64 libcom_err-1.42.9-7.el7.x86_64 libevent-2.0.21-4.el7.x86_64 libffi-3.0.13-16.el7.x86_64 libselinux-2.2.2-6.el7.x86_64 lua-5.1.4-14.el7.x86_64 openssl-libs-1.0.1e-51.el7_2.5.x86_64 pcre-8.32-15.el7_2.1.x86_64 sqlite-3.7.17-8.el7.x86_64 xz-libs-5.1.2-12alpha.el7.x86_64 zlib-1.2.7-15.el7.x86_64
(gdb) where
#0  0x00007fc66e81b1ca in readdir_r () from /lib64/libc.so.6
#1  0x00000000004258a5 in rspamc_process_dir (cmd=<optimized out>, attrs=0xd37e00, name=0x7fff376087c9 "spam", ev_base=0xd70c40)
    at /usr/src/debug/rspamd-1.4.0/src/client/rspamc.c:1440
#2  main (argc=2, argv=0x7fff37607938, env=<optimized out>) at /usr/src/debug/rspamd-1.4.0/src/client/rspamc.c:1621
(gdb) q

`````

**Comment by smfreegard** [comment]
Fixed in 82bb01e
