### ISSUE TITLE
Normal process crashes

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rspamd#1080]
Looks like related to c0e7b579a46a74bb6617eb331783f59123afad52
```cxx
# gdb `which rspamd` -c ./rspamd-1.4.0.core
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "i386-marcel-freebsd"...

warning: core file may not match specified executable file.
Core was generated by `rspamd-1.4.0'.
Program terminated with signal 11, Segmentation fault.
Reading symbols from /usr/local/lib/libfann.so.2...done.
Loaded symbols for /usr/local/lib/libfann.so.2
Reading symbols from /lib/libutil.so.9...done.
Loaded symbols for /lib/libutil.so.9
Reading symbols from /usr/local/lib/libglib-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libglib-2.0.so.0
Reading symbols from /usr/local/lib/libintl.so.8...done.
Loaded symbols for /usr/local/lib/libintl.so.8
Reading symbols from /usr/local/lib/libgmodule-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libgmodule-2.0.so.0
Reading symbols from /usr/local/lib/libpcre.so.1...done.
Loaded symbols for /usr/local/lib/libpcre.so.1
Reading symbols from /usr/local/lib/libgmime-2.6.so.0...done.
Loaded symbols for /usr/local/lib/libgmime-2.6.so.0
Reading symbols from /usr/local/lib/libgio-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libgio-2.0.so.0
Reading symbols from /usr/local/lib/libgobject-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libgobject-2.0.so.0
Reading symbols from /usr/local/lib/libgthread-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libgthread-2.0.so.0
Reading symbols from /usr/local/lib/libevent-2.0.so.5...done.
Loaded symbols for /usr/local/lib/libevent-2.0.so.5
Reading symbols from /usr/local/lib/libsqlite3.so.0...done.
Loaded symbols for /usr/local/lib/libsqlite3.so.0
Reading symbols from /usr/local/lib/libiconv.so.2...done.
Loaded symbols for /usr/local/lib/libiconv.so.2
Reading symbols from /lib/libcrypto.so.7...done.
Loaded symbols for /lib/libcrypto.so.7
Reading symbols from /usr/lib/libssl.so.7...done.
Loaded symbols for /usr/lib/libssl.so.7
Reading symbols from /usr/lib/libmagic.so.4...done.
Loaded symbols for /usr/lib/libmagic.so.4
Reading symbols from /lib/libm.so.5...done.
Loaded symbols for /lib/libm.so.5
Reading symbols from /usr/local/lib/libluajit-5.1.so.2...done.
Loaded symbols for /usr/local/lib/libluajit-5.1.so.2
Reading symbols from /usr/local/lib/rspamd/librspamd-actrie.so...done.
Loaded symbols for /usr/local/lib/rspamd/librspamd-actrie.so
Reading symbols from /lib/libthr.so.3...done.
Loaded symbols for /lib/libthr.so.3
Reading symbols from /lib/libc.so.7...done.
Loaded symbols for /lib/libc.so.7
Reading symbols from /lib/libz.so.6...done.
Loaded symbols for /lib/libz.so.6
Reading symbols from /usr/local/lib/libffi.so.6...done.
Loaded symbols for /usr/local/lib/libffi.so.6
Reading symbols from /lib/libgcc_s.so.1...done.
Loaded symbols for /lib/libgcc_s.so.1
Reading symbols from /usr/lib/i18n/libiconv_std.so.4...done.
Loaded symbols for /usr/lib/i18n/libiconv_std.so.4
Reading symbols from /usr/lib/i18n/libUTF8.so.4...done.
Loaded symbols for /usr/lib/i18n/libUTF8.so.4
Reading symbols from /usr/lib/i18n/libmapper_zone.so.4...done.
Loaded symbols for /usr/lib/i18n/libmapper_zone.so.4
Reading symbols from /usr/lib/i18n/libmapper_none.so.4...done.
Loaded symbols for /usr/lib/i18n/libmapper_none.so.4
Reading symbols from /libexec/ld-elf.so.1...done.
Loaded symbols for /libexec/ld-elf.so.1
#0  0x0819c74b in insert_metric_result (task=0x31614008, metric=0x294e9300, symbol=0x3173c1f0 "RECEIVED_SPAMHAUS", flag=1, opts=0x2968ad50, single=0)
    at /usr/home/moiseev/ports/rspamd-devel/work/rspamd-0bd145a/src/libmime/filter.c:145
145     /usr/home/moiseev/ports/rspamd-devel/work/rspamd-0bd145a/src/libmime/filter.c: Нет такого файла или каталога.
        in /usr/home/moiseev/ports/rspamd-devel/work/rspamd-0bd145a/src/libmime/filter.c
[New Thread 29403080 (LWP 100162/<unknown>)]
(gdb) bt full
#0  0x0819c74b in insert_metric_result (task=0x31614008, metric=0x294e9300, symbol=0x3173c1f0 "RECEIVED_SPAMHAUS", flag=1, opts=0x2968ad50, single=0)
    at /usr/home/moiseev/ports/rspamd-devel/work/rspamd-0bd145a/src/libmime/filter.c:145
        metric_res = (struct metric_result *) 0x31617df0
        s = (struct symbol *) 0x3173c160
        w = 0
        gr_score = (gdouble *) 0x0
        sdef = (struct rspamd_symbol_def *) 0x0
        gr = (struct rspamd_symbols_group *) 0x0
        mobj = (const ucl_object_t *) 0x315a2cd0
        sobj = (const ucl_object_t *) 0x0
#1  0x0819b810 in insert_result_common (task=0x31614008, symbol=0x3173c1f0 "RECEIVED_SPAMHAUS", flag=1, opts=0x2968ad50, single=0)
    at /usr/home/moiseev/ports/rspamd-devel/work/rspamd-0bd145a/src/libmime/filter.c:233
        metric = (struct metric *) 0xbfbfd372
        cur = (GList *) 0x28472998
        metric_list = (GList *) 0x0
#2  0x0819b6bb in rspamd_task_insert_result (task=0x31614008, symbol=0x3173c1f0 "RECEIVED_SPAMHAUS", flag=1, opts=0x2968ad50)
    at /usr/home/moiseev/ports/rspamd-devel/work/rspamd-0bd145a/src/libmime/filter.c:259
No locals.
#3  0x080e4962 in lua_task_insert_result (L=0x28d421c0) at /usr/home/moiseev/ports/rspamd-devel/work/rspamd-0bd145a/src/lua/lua_task.c:1057
        task = (struct rspamd_task *) 0x31614008
        symbol_name = (const gchar *) 0x3173c1f0 "RECEIVED_SPAMHAUS"
        param = (const gchar *) 0x28eb0ef0 "1.158.251.89.zen.spamhaus.org"
        flag = 1
        params = (GList *) 0x2968ad50
        i = 5
        top = 4
#4  0x28af9c8d in ?? () from /usr/local/lib/libluajit-5.1.so.2
No symbol table info available.
#5  0x28b0a0e4 in lua_pcall () from /usr/local/lib/libluajit-5.1.so.2
No symbol table info available.
#6  0x08105b48 in lua_dns_callback (reply=0x31609700, arg=0x3173bd40) at /usr/home/moiseev/ports/rspamd-devel/work/rspamd-0bd145a/src/lua/lua_dns.c:209
        cd = (struct lua_dns_cbdata *) 0x3173bd40
        i = 2
        presolver = (struct rspamd_dns_resolver **) 0x28ea5848
        elt = (struct rdns_reply_entry *) 0x0
        addr = (rspamd_inet_addr_t *) 0x3161e278
#7  0x08140c4a in rspamd_dns_callback (reply=0x31609700, ud=0x3173bd80) at /usr/home/moiseev/ports/rspamd-devel/work/rspamd-0bd145a/src/libserver/dns.c:69
        reqdata = (struct rspamd_dns_request_ud *) 0x3173bd80
#8  0x08286bf9 in rdns_process_read (fd=29, arg=0x296480d0) at /usr/home/moiseev/ports/rspamd-devel/work/rspamd-0bd145a/contrib/librdns/resolver.c:281
        ioc = (struct rdns_io_channel *) 0x296480d0
        resolver = (struct rdns_resolver *) 0x2970b540
        req = (struct rdns_request *) 0x31612e00
        r = 2285
        rep = (struct rdns_reply *) 0x31609700
        in = "lZ\201\200\000\001\000\002\000\024\000^\0011\003158\003251\00289\003zen\bspamhaus\003org\000\000\001\000\001ю\f\000\001\000\001\000\000\003e\000\004\177\000\000\vю\f\000\001\000\001\000\000\003e\000\004\177\000\000\004ю\031\000\002\000\001\000\000\002Z\000\a\0013\002nsю\035ю\031\000\002\000\001\000\000\002Z\000\004\001iю]ю\031\000\002\000\001\000\000\002Z\000\004\001xю]ю\031\000\002\000\001\000\000\002Z\000\004\001gю]ю\031\000\002\000\001\000\000\002Z\000\004\0010ю]ю\031\000\002\000\001\000\000\002Z\000\004\001oю]ю\031\000\002\000\001\000\000\002Z\000\004\001cю]ю\031\000\002\000\001"...
#9  0x08142224 in rdns_libevent_read_event (fd=29, what=2, ud=0x296480d0) at rdns_event.h:82
No locals.
#10 0x286ef842 in event_base_loop () from /usr/local/lib/libevent-2.0.so.5
No symbol table info available.
#11 0x08070fd4 in start_worker (worker=0x29687160) at /usr/home/moiseev/ports/rspamd-devel/work/rspamd-0bd145a/src/worker.c:631
        ctx = (struct rspamd_worker_ctx *) 0x294c55b0
        lp = (struct rspamd_worker_log_pipe *) 0x2
        ltmp = (struct rspamd_worker_log_pipe *) 0x8341b50
#12 0x0817d7b1 in rspamd_fork_worker (rspamd_main=0x2940ddc0, cf=0x2970b480, index=1, ev_base=0x294d8880) at /usr/home/moiseev/ports/rspamd-devel/work/rspamd-0bd145a/src/libserver/worker_util.c:618
        wrk = (struct rspamd_worker *) 0x29687160
        rc = 0
        rlim = {rlim_cur = 104857600, rlim_max = 104857600}
#13 0x080702f8 in rspamd_fork_delayed_cb (signo=-1, what=1, arg=0x297294b0) at /usr/home/moiseev/ports/rspamd-devel/work/rspamd-0bd145a/src/rspamd.c:317
        w = (struct waiting_worker *) 0x297294b0
---Type <return> to continue, or q <return> to quit---
#14 0x286ef746 in event_base_loop () from /usr/local/lib/libevent-2.0.so.5
No symbol table info available.
#15 0x0806c779 in main (argc=1, argv=0xbfbfed30, env=0xbfbfed50) at /usr/home/moiseev/ports/rspamd-devel/work/rspamd-0bd145a/src/rspamd.c:1347
        i = 1
        res = 0
        signals = {__sigaction_u = {__sa_handler = 0, __sa_sigaction = 0}, sa_flags = 0, sa_mask = {__bits = {0, 0, 0, 0}}}
        sigpipe_act = {__sigaction_u = {__sa_handler = 0x1, __sa_sigaction = 0x1}, sa_flags = 0, sa_mask = {__bits = {4096, 0, 0, 0}}}
        pworker = (worker_t **) 0x834288c
        type = 101
        control_addr = (rspamd_inet_addr_t *) 0x294132a0
        ev_base = (struct event_base *) 0x294d8880
        term_ev = {ev_active_next = {tqe_next = 0x28b88880, tqe_prev = 0x8341da0}, ev_next = {tqe_next = 0xbfbfebe8, tqe_prev = 0x294d8954}, ev_timeout_pos = {ev_next_with_common_timeout = {
      tqe_next = 0xffffffff, tqe_prev = 0x283308d7}, min_heap_idx = -1}, ev_fd = 15, ev_base = 0x294d8880, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x29741780}, ev_timeout = {tv_sec = 0,
        tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x29741780}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, ev_pri = 0 '\0',
  ev_closure = 1 '\001', ev_timeout = {tv_sec = 0, tv_usec = 674520372}, ev_callback = 0x806d610 <rspamd_term_handler>, ev_arg = 0x2940ddc0}
        int_ev = {ev_active_next = {tqe_next = 0x28b80378, tqe_prev = 0xbfbfec04}, ev_next = {tqe_next = 0xbfbfeb58, tqe_prev = 0x294d8954}, ev_timeout_pos = {ev_next_with_common_timeout = {
      tqe_next = 0xffffffff, tqe_prev = 0x294031ac}, min_heap_idx = -1}, ev_fd = 2, ev_base = 0x294d8880, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x29741788}, ev_timeout = {tv_sec = 0,
        tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x29741788}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, ev_pri = 0 '\0',
  ev_closure = 1 '\001', ev_timeout = {tv_sec = 674520320, tv_usec = -1077941184}, ev_callback = 0x806d610 <rspamd_term_handler>, ev_arg = 0x2940ddc0}
        cld_ev = {ev_active_next = {tqe_next = 0x0, tqe_prev = 0x29741778}, ev_next = {tqe_next = 0xbfbfeb10, tqe_prev = 0x294d8954}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0xffffffff,
      tqe_prev = 0x0}, min_heap_idx = -1}, ev_fd = 20, ev_base = 0x294d8880, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x29741798}, ev_timeout = {tv_sec = 0, tv_usec = 0}}, ev_signal = {
      ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x29741798}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 8, ev_flags = 128, ev_pri = 0 '\0', ev_closure = 1 '\001', ev_timeout = {
    tv_sec = 0, tv_usec = 674520320}, ev_callback = 0x806d850 <rspamd_cld_handler>, ev_arg = 0x2940ddc0}
        hup_ev = {ev_active_next = {tqe_next = 0x28354200, tqe_prev = 0x28354400}, ev_next = {tqe_next = 0xbfbfeba0, tqe_prev = 0x294d8954}, ev_timeout_pos = {ev_next_with_common_timeout = {
      tqe_next = 0xffffffff, tqe_prev = 0x28354c00}, min_heap_idx = -1}, ev_fd = 1, ev_base = 0x294d8880, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x29741790}, ev_timeout = {
        tv_sec = 674562048, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x29741790}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128,
  ev_pri = 0 '\0', ev_closure = 1 '\001', ev_timeout = {tv_sec = 0, tv_usec = 674434635}, ev_callback = 0x806d700 <rspamd_hup_handler>, ev_arg = 0x2940ddc0}
        usr1_ev = {ev_active_next = {tqe_next = 0x28ba0820, tqe_prev = 0xbfbfec70}, ev_next = {tqe_next = 0x29687060, tqe_prev = 0x294d8954}, ev_timeout_pos = {ev_next_with_common_timeout = {
      tqe_next = 0xffffffff, tqe_prev = 0x2834a000}, min_heap_idx = -1}, ev_fd = 30, ev_base = 0x294d8880, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x297417a0}, ev_timeout = {
        tv_sec = 674496512, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x297417a0}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128,
  ev_pri = 0 '\0', ev_closure = 1 '\001', ev_timeout = {tv_sec = 674540032, tv_usec = 674540544}, ev_callback = 0x806de70 <rspamd_usr1_handler>, ev_arg = 0x2940ddc0}
        control_ev = {ev_active_next = {tqe_next = 0x0, tqe_prev = 0x29741778}, ev_next = {tqe_next = 0x296872e0, tqe_prev = 0x294d8954}, ev_timeout_pos = {ev_next_with_common_timeout = {
      tqe_next = 0xffffffff, tqe_prev = 0x28345d00}, min_heap_idx = -1}, ev_fd = 5, ev_base = 0x294d8880, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x29738c00}, ev_timeout = {tv_sec = 0,
        tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x29738c00}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 18, ev_res = 2, ev_flags = 128, ev_pri = 0 '\0',
  ev_closure = 2 '\002', ev_timeout = {tv_sec = -225447180, tv_usec = 674534432}, ev_callback = 0x806ead0 <rspamd_control_handler>, ev_arg = 0x2940ddc0}
        term_tv = {tv_sec = 683280416, tv_usec = -1077941136}
        rspamd_main = (struct rspamd_main *) 0x2940ddc0
Current language:  auto; currently minimal
(gdb)
```

**Comment by moisseev** [comment]
Fixed with c5acf4d64f4dda5e0a033955f6171549a02f94b2
