### ISSUE TITLE
Saving actions in Web-UI crashes rspamd

### ISSUE THREAD

**Issue by skibbipl** [vstakhov/rspamd#1497]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.5.2, debian package
### Operation system, CPU, memory and environment:
Debian 9.0 (unstable), Intel(R) Core(TM)2 Duo CPU     E7500  @ 2.93GHz
### Description (Please provide a descriptive summary of the issue):
Whenever I try to save Actions values in Configuration rspamd crashes.
### Compile errors (if any):
N/A
### Steps to reproduce:
1. Login to web controller
2. Select Configuration
3. Change actions values
4. Press Save actions button
### Expected results:
Rspamd not crashing
### Actual results:
Rspamd crashes
### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):
```
#0  0x00007fe8277b01dc in free () from /usr/lib/x86_64-linux-gnu/libjemalloc.so.1
No symbol table info available.
#1  0x00005637e1b3c4ec in ucl_object_iterate_free (it=<optimized out>) at ./contrib/libucl/ucl_util.c:2537
        rit = 0x7fe815e13500
        __PRETTY_FUNCTION__ = "ucl_object_iterate_free"
#2  0x00005637e1a0b683 in rspamd_controller_handle_saveactions (conn_ent=conn_ent@entry=0x7fe81fb00f00, msg=msg@entry=0x7fe81f8378a0) at ./src/controller.c:2057
        session = 0x7fe81fac1000
        parser = <optimized out>
        metric = 0x7fe81f9632e0
        obj = 0x7fe8163fa700
        cur = <optimized out>
        ctx = 0x7fe81f969710
        error = <optimized out>
        score = <optimized out>
        i = 3
        added = 0
        it = 0x7fe815e13500
        __func__ = "rspamd_controller_handle_saveactions"
#3  0x00005637e1b0275b in rspamd_http_router_finish_handler (conn=<optimized out>, msg=0x7fe81f8378a0) at ./src/libutil/http.c:3178
        entry = 0x7fe81fb00f00
        handler = 0x5637e1a0b3c0 <rspamd_controller_handle_saveactions>
        found = 0x5637e1a0b3c0 <rspamd_controller_handle_saveactions>
        err = <optimized out>
        lookup = {len = 12, begin = 0x7fe815e02d90 "/saveactionsKeep-Alive\r\n q=0.01\r\n\r\n.5,bg;q=0.3\r\n\b"}
        u = {field_set = 8, port = 0, field_data = {{off = 0, len = 0}, {off = 44309, len = 9688}, {off = 32744, len = 0}, {off = 0, len = 12}, {off = 32744, len = 0}, {off = 38560, len = 5594}, {off = 32744, len = 0}}}
        i = <optimized out>
        re = <optimized out>
        router = 0x7fe81f842d60
        __func__ = "rspamd_http_router_finish_handler"
#4  0x00005637e1b0c83f in rspamd_http_on_message_complete (parser=<optimized out>) at ./src/libutil/http.c:960
        conn = 0x7fe81fac25e0
        priv = 0x7fe815da9610
        ret = <optimized out>
        mode = <optimized out>
        __func__ = "rspamd_http_on_message_complete"
#5  0x00005637e1a8c91a in http_parser_execute (parser=<optimized out>, settings=<optimized out>, data=<optimized out>, len=<optimized out>, len=<optimized out>, data=<optimized out>, settings=<optimized out>, parser=<optimized out>) at ./contrib/http-parser/http_parser.c:1772
        c = <optimized out>
        header_value_mark = 0x0
        ch = 91 '['
        unhex_val = <optimized out>
        p = 0x7fe815e1a019 "]actions HTTP/1.1\r\nHost: localhost:11334\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0 OWASMIME/4.0500\r\nAccept: application/json, text/javascript, */*; q="...
        header_field_mark = <optimized out>
        url_mark = <optimized out>
        body_mark = <optimized out>
        status_mark = <optimized out>
        len = <optimized out>
        data = 0x7fe815e1a010 "\r\n[15,6,4]actions HTTP/1.1\r\nHost: localhost:11334\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0 OWASMIME/4.0500\r\nAccept: application/json, text/javascript"...
        settings = <optimized out>
        parser = 0x7fe815da9640
        p = 0x7fe815e1a010 "\r\n[15,6,4]actions HTTP/1.1\r\nHost: localhost:11334\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0 OWASMIME/4.0500\r\nAccept: application/json, text/javascript"...
#6  0x00005637e1b0c581 in rspamd_http_event_handler.lto_priv.4021 (fd=<optimized out>, what=<optimized out>, ud=0x7fe81fac25e0) at ./src/libutil/http.c:1177
        conn = 0x7fe81fac25e0
        priv = 0x7fe815da9610
        pbuf = 0x7fe81fb004f0
        d = 0x7fe815e1a010 "\r\n[15,6,4]actions HTTP/1.1\r\nHost: localhost:11334\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0 OWASMIME/4.0500\r\nAccept: application/json, text/javascript"...
        r = 10
        err = <optimized out>
#7  0x00007fe825d7a5a0 in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
No symbol table info available.
#8  0x00005637e1a0863c in start_controller_worker (worker=0x7fe815dacd00) at ./src/controller.c:3609
        ctx = 0x7fe81f969710
        mctx = <optimized out>
        iter = {dummy1 = 0x7fe81fabea40, dummy2 = 0x7fe82729b379 <fcntl+57>, dummy3 = 0x10, dummy4 = 8, dummy5 = 0, dummy6 = 0x3}
        key = 0x5637e1f82fba
        value = 0x7fe81faec148
        cache = <optimized out>
        m = <optimized out>
        __func__ = "start_controller_worker"
#9  0x00005637e1abb7e3 in rspamd_fork_worker (rspamd_main=0x7fe81f864080, cf=0x7fe81f842c80, index=0, ev_base=<optimized out>) at ./src/libserver/worker_util.c:607
        wrk = 0x7fe815dacd00
        rc = <optimized out>
        rlim = {rlim_cur = 104857600, rlim_max = 104857600}
        __func__ = "rspamd_fork_worker"
#10 0x00005637e1a01993 in spawn_worker_type (rspamd_main=<optimized out>, ev_base=<optimized out>, cf=<optimized out>, cf=<optimized out>, ev_base=<optimized out>, rspamd_main=<optimized out>) at ./src/rspamd.c:521
        i = 0
#11 0x00005637e1a01c3a in spawn_workers (rspamd_main=0x7fe81f864080, ev_base=0x7fe81f8cd980) at ./src/rspamd.c:605
        cur = 0x7fe81f816960
        ls = <optimized out>
        cf = <optimized out>
        p = <optimized out>
        bcf = <optimized out>
        listen_ok = <optimized out>
        seen_mandatory_workers = 0x7fe81fafe940
        cw = <optimized out>
        wrk = <optimized out>
        i = <optimized out>
        __func__ = "spawn_workers"
#12 0x00005637e19fd16b in main (argc=<optimized out>, argv=<optimized out>, env=<optimized out>) at ./src/rspamd.c:1376
        i = <optimized out>
        res = 0
        signals = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = 0, sa_restorer = 0x0}
        sigpipe_act = {__sigaction_handler = {sa_handler = 0x1, sa_sigaction = 0x1}, sa_mask = {__val = {4096, 0 <repeats 15 times>}}, sa_flags = 0, sa_restorer = 0x3ff000000000000}
        pworker = <optimized out>
        type = <optimized out>
        control_addr = 0x7fe81fafe2f0
        ev_base = 0x7fe81f8cd980
        term_ev = {ev_active_next = {tqe_next = 0x0, tqe_prev = 0x0}, ev_next = {tqe_next = 0x7ffd64b09880, tqe_prev = 0x7fe81f8cdae0}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0xffffffff, tqe_prev = 0x7fe827bf6858}, min_heap_idx = -1}, ev_fd = 15, ev_base = 0x7fe81f8cd980, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0,
                tqe_prev = 0x7fe81fae2270}, ev_timeout = {tv_sec = 140635075969024, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x7fe81fae2270}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, ev_pri = 0 '\000', ev_closure = 1 '\001', ev_timeout = {tv_sec = 725871085, tv_usec = 4294967295},
          ev_callback = 0x5637e1a013b0 <rspamd_term_handler>, ev_arg = 0x7fe81f864080}
        int_ev = {ev_active_next = {tqe_next = 0x7ffd64b098b4, tqe_prev = 0x7ffd64b09980}, ev_next = {tqe_next = 0x7ffd64b09760, tqe_prev = 0x7fe81f8cdae0}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0xffffffff, tqe_prev = 0x0}, min_heap_idx = -1}, ev_fd = 2, ev_base = 0x7fe81f8cd980, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0,
                tqe_prev = 0x7fe81fae22a0}, ev_timeout = {tv_sec = 140726292709376, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x7fe81fae22a0}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, ev_pri = 0 '\000', ev_closure = 1 '\001', ev_timeout = {tv_sec = 0, tv_usec = 140726292748872},
          ev_callback = 0x5637e1a013b0 <rspamd_term_handler>, ev_arg = 0x7fe81f864080}
        cld_ev = {ev_active_next = {tqe_next = 0x7fe827bf84e8, tqe_prev = 0x7fe826753d90}, ev_next = {tqe_next = 0x7ffd64b096d0, tqe_prev = 0x7fe81f8cdae0}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0xffffffff, tqe_prev = 0x7fe826761038}, min_heap_idx = -1}, ev_fd = 17, ev_base = 0x7fe81f8cd980, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0,
                tqe_prev = 0x7fe81fae2280}, ev_timeout = {tv_sec = 140635036647424, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x7fe81fae2280}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, ev_pri = 0 '\000', ev_closure = 1 '\001', ev_timeout = {tv_sec = 725871085, tv_usec = 11341735},
          ev_callback = 0x5637e1a01410 <rspamd_cld_handler>, ev_arg = 0x7fe81f864080}
        hup_ev = {ev_active_next = {tqe_next = 0x7fe82623a495, tqe_prev = 0x7fe8279ec124}, ev_next = {tqe_next = 0x7ffd64b097f0, tqe_prev = 0x7fe81f8cdae0}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0x7fe8ffffffff, tqe_prev = 0x7fe826753d90}, min_heap_idx = -1}, ev_fd = 1, ev_base = 0x7fe81f8cd980, _ev = {ev_io = {ev_io_next = {
                tqe_next = 0x0, tqe_prev = 0x7fe81fae2250}, ev_timeout = {tv_sec = 140635075969024, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x7fe81fae2250}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, ev_pri = 0 '\000', ev_closure = 1 '\001', ev_timeout = {tv_sec = 140635073856219,
            tv_usec = 140635032381802}, ev_callback = 0x5637e1a022d0 <rspamd_hup_handler>, ev_arg = 0x7fe81f864080}
        usr1_ev = {ev_active_next = {tqe_next = 0x7ffd64b09704, tqe_prev = 0x7ffd64b097d0}, ev_next = {tqe_next = 0x7fe81f8cd9a8, tqe_prev = 0x7fe81f8cdae0}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0xffffffff, tqe_prev = 0x7fe8279ec050}, min_heap_idx = -1}, ev_fd = 10, ev_base = 0x7fe81f8cd980, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0,
                tqe_prev = 0x7fe81fae2290}, ev_timeout = {tv_sec = 140635071447040, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x7fe81fae2290}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, ev_pri = 0 '\000', ev_closure = 1 '\001', ev_timeout = {tv_sec = 140635071498968,
            tv_usec = 140635076052304}, ev_callback = 0x5637e1a017a0 <rspamd_usr1_handler>, ev_arg = 0x7fe81f864080}
        control_ev = {ev_active_next = {tqe_next = 0x7fe827c08700, tqe_prev = 0x7ffd64b911a8}, ev_next = {tqe_next = 0x7ffd64b91298, tqe_prev = 0x7fe8279ec963}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0x2, tqe_prev = 0x7ffd64b91298}, min_heap_idx = 2}, ev_fd = 666928896, ev_base = 0x7ffd64b09708, _ev = {ev_io = {ev_io_next = {
                tqe_next = 0x7ffd64b09704, tqe_prev = 0x7fe8279ec963}, ev_timeout = {tv_sec = 140635055795221, tv_usec = 140726292748448}}, ev_signal = {ev_signal_next = {tqe_next = 0x7ffd64b09704, tqe_prev = 0x7fe8279ec963}, ev_ncalls = 11285, ev_pncalls = 0x7ffd64b098a0}}, ev_events = -26872, ev_res = 25776, ev_flags = 32765, ev_pri = 0 '\000',
          ev_closure = 0 '\000', ev_timeout = {tv_sec = 2954611200, tv_usec = 46165800}, ev_callback = 0x7ffd64b91298, ev_arg = 0x7ffd64b097e0}
        term_tv = {tv_sec = 32988842, tv_usec = 2}
        __func__ = "main"
```

**Comment by vstakhov** [comment]
I have fixed this issue hopefully.
