### ISSUE TITLE
normal process segfaults periodically

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rspamd#1638]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [x] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.0-git.c6673ac

### Operation system, CPU, memory and environment:
```
# freebsd-version -ku
11.0-RELEASE-p2
11.0-RELEASE-p7
```

### Description (Please provide a descriptive summary of the issue):
```
2017-05-12 09:48:25 #2232(main) <750f99>; main; rspamd_cld_handler: normal process 2235 terminated abnormally by signal: Segmentation fault and created core file
```

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):

```cxx
# gdb `which rspamd` -c /coreland/rspamd-1.6.0.core
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...

warning: core file may not match specified executable file.
Core was generated by `rspamd-1.6.0'.
Program terminated with signal 11, Segmentation fault.
Reading symbols from /usr/local/lib/libfann.so.2...done.
Loaded symbols for /usr/local/lib/libfann.so.2
Reading symbols from /lib/libutil.so.9...done.
Loaded symbols for /lib/libutil.so.9
Reading symbols from /usr/local/lib/libgthread-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libgthread-2.0.so.0
Reading symbols from /usr/local/lib/libglib-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libglib-2.0.so.0
Reading symbols from /usr/local/lib/libintl.so.8...done.
Loaded symbols for /usr/local/lib/libintl.so.8
Reading symbols from /usr/local/lib/libpcre.so.1...done.
Loaded symbols for /usr/local/lib/libpcre.so.1
Reading symbols from /usr/local/lib/libevent-2.1.so.6...done.
Loaded symbols for /usr/local/lib/libevent-2.1.so.6
Reading symbols from /usr/local/lib/libsqlite3.so.0...done.
Loaded symbols for /usr/local/lib/libsqlite3.so.0
Reading symbols from /usr/local/lib/libicui18n.so.58...done.
Loaded symbols for /usr/local/lib/libicui18n.so.58
Reading symbols from /usr/local/lib/libicuuc.so.58...done.
Loaded symbols for /usr/local/lib/libicuuc.so.58
Reading symbols from /usr/local/lib/libicudata.so.58...
warning: Lowest section in /usr/local/lib/libicudata.so.58 is .hash at 0000000000000120
done.
Loaded symbols for /usr/local/lib/libicudata.so.58
Reading symbols from /lib/libcrypto.so.8...done.
Loaded symbols for /lib/libcrypto.so.8
Reading symbols from /usr/lib/libssl.so.8...done.
Loaded symbols for /usr/lib/libssl.so.8
Reading symbols from /usr/lib/libmagic.so.4...done.
Loaded symbols for /usr/lib/libmagic.so.4
Reading symbols from /lib/libm.so.5...done.
Loaded symbols for /lib/libm.so.5
Reading symbols from /usr/local/lib/libgd.so.6...done.
Loaded symbols for /usr/local/lib/libgd.so.6
Reading symbols from /lib/libthr.so.3...done.
Loaded symbols for /lib/libthr.so.3
Reading symbols from /usr/local/lib/libluajit-5.1.so.2...done.
Loaded symbols for /usr/local/lib/libluajit-5.1.so.2
Reading symbols from /usr/local/lib/rspamd/librspamd-actrie.so...done.
Loaded symbols for /usr/local/lib/rspamd/librspamd-actrie.so
Reading symbols from /lib/libc.so.7...done.
Loaded symbols for /lib/libc.so.7
Reading symbols from /usr/local/lib/libiconv.so.2...done.
Loaded symbols for /usr/local/lib/libiconv.so.2
Reading symbols from /usr/lib/libc++.so.1...done.
Loaded symbols for /usr/lib/libc++.so.1
Reading symbols from /lib/libcxxrt.so.1...done.
Loaded symbols for /lib/libcxxrt.so.1
Reading symbols from /lib/libgcc_s.so.1...done.
Loaded symbols for /lib/libgcc_s.so.1
Reading symbols from /lib/libz.so.6...done.
Loaded symbols for /lib/libz.so.6
Reading symbols from /usr/local/lib/libpng16.so.16...done.
Loaded symbols for /usr/local/lib/libpng16.so.16
Reading symbols from /usr/local/lib/libfontconfig.so.1...done.
Loaded symbols for /usr/local/lib/libfontconfig.so.1
Reading symbols from /usr/local/lib/libfreetype.so.6...done.
Loaded symbols for /usr/local/lib/libfreetype.so.6
Reading symbols from /usr/local/lib/libjpeg.so.8...done.
Loaded symbols for /usr/local/lib/libjpeg.so.8
Reading symbols from /usr/local/lib/libtiff.so.5...done.
Loaded symbols for /usr/local/lib/libtiff.so.5
Reading symbols from /usr/local/lib/libwebp.so.7...done.
Loaded symbols for /usr/local/lib/libwebp.so.7
Reading symbols from /usr/local/lib/libexpat.so.1...done.
Loaded symbols for /usr/local/lib/libexpat.so.1
Reading symbols from /usr/lib/libbz2.so.4...done.
Loaded symbols for /usr/lib/libbz2.so.4
Reading symbols from /usr/lib/liblzma.so.5...done.
Loaded symbols for /usr/lib/liblzma.so.5
Reading symbols from /usr/local/lib/libjbig.so.2...done.
Loaded symbols for /usr/local/lib/libjbig.so.2
Reading symbols from /libexec/ld-elf.so.1...done.
Loaded symbols for /libexec/ld-elf.so.1
#0  0x000000000045b59d in rspamd_lru_hash_remove_evicted (hash=0x8069e2a20, elt=0x81996daf0) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-c6673ac/src/libutil/hash.c:87
87      /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-c6673ac/src/libutil/hash.c: No such file or directory.
        in /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-c6673ac/src/libutil/hash.c
[New Thread 806816000 (LWP 101869/<unknown>)]
(gdb) bt full
#0  0x000000000045b59d in rspamd_lru_hash_remove_evicted (hash=0x8069e2a20, elt=0x81996daf0) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-c6673ac/src/libutil/hash.c:87
        i = 1
#1  0x000000000045af3b in rspamd_lru_hash_remove_node (hash=0x8069e2a20, elt=0x81996daf0) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-c6673ac/src/libutil/hash.c:195
No locals.
#2  0x000000000045b1b9 in rspamd_lru_hash_insert (hash=0x8069e2a20, key=0x819906d40, value=0x819909240, now=1494571704, ttl=0)
    at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-c6673ac/src/libutil/hash.c:335
        res = (rspamd_lru_element_t *) 0x81996daf0
#3  0x0000000000546e89 in lua_dkim_sign_handler (L=0x1378) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-c6673ac/src/plugins/dkim_check.c:616
        task = (struct rspamd_task *) 0x80cfdc800
        err = (GError *) 0x0
        hdr = (GString *) 0x60199e
        selector = (const gchar *) 0x3c878 "dkim"
        domain = (const gchar *) 0xe7fc8 "mezonplus.ru"
        key = (const gchar *) 0x6e3d0 "/usr/local/etc/dkim/mezonplus.ru.dkim.key"
        rawkey = (const gchar *) 0x0
        ctx = (rspamd_dkim_sign_context_t *) 0x69bb40
        dkim_key = (rspamd_dkim_sign_key_t *) 0x819909240
        rawlen = 0
#4  0x00000008039bf1d6 in ?? () from /usr/local/lib/libluajit-5.1.so.2
No symbol table info available.
#5  0x00000008039d0e41 in lua_pcall () from /usr/local/lib/libluajit-5.1.so.2
No symbol table info available.
#6  0x00000000004a1fa6 in lua_metric_symbol_callback (task=0x80cfdc800, ud=0x80702e758) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-c6673ac/src/lua/lua_config.c:1035
        cd = (struct lua_callback_data *) 0x80702e758
        ptask = (struct rspamd_task **) 0x12e488
        level = 1
        nresults = 4767842
        err_idx = 1
        ret = -8752
        L = (lua_State *) 0x1378
        tb = (GString *) 0x8068d2680
        s = (struct rspamd_symbol_result *) 0x803f7d8c1
#7  0x00000000004f9ec9 in rspamd_symbols_cache_check_symbol (task=0x80cfdc800, cache=0x806824830, item=0x807035e00, checkpoint=0x819941c48, total_diff=0x7fffffffdf60)
    at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-c6673ac/src/libserver/symbols_cache.c:1287
        pending_before = 2
        pending_after = 1
        t1 = 1285962.785542028
        t2 = 0
        diff = 3.2882766329161251e-317
        ptask = (struct rspamd_task **) 0x7fffffffdd90
        L = (lua_State *) 0x7fffffffde90
        check = 1
        slow_diff_limit = 100000
#8  0x00000000004f9442 in rspamd_symbols_cache_process_symbols (task=0x80cfdc800, cache=0x806824830, stage=16)
    at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-c6673ac/src/libserver/symbols_cache.c:1717
        item = (struct cache_item *) 0x807035e00
        checkpoint = (struct cache_savepoint *) 0x819941c48
        i = 309
        total_microseconds = 1426.0050375014544
        all_done = 8
        saved_priority = 428833228
        max_microseconds = 300000
        start_events_pending = 0
#9  0x00000000004fd72a in rspamd_task_process (task=0x80cfdc800, stages=16383) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-c6673ac/src/libserver/task.c:708
        st = 16
        ret = 1
        stat_error = (GError *) 0x0
#10 0x00000000004fdb2c in rspamd_task_process (task=0x80cfdc800, stages=16383) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-c6673ac/src/libserver/task.c:806
        st = 8
        ret = 1
        stat_error = (GError *) 0x0
---Type <return> to continue, or q <return> to quit---
#11 0x00000000004fd47c in rspamd_task_fin (arg=0x80cfdc800) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-c6673ac/src/libserver/task.c:163
        task = (struct rspamd_task *) 0x80cfdc800
#12 0x00000000004de11c in rspamd_session_pending (session=0x8199ed020) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-c6673ac/src/libserver/events.c:276
        ret = 1
#13 0x00000000004de020 in rspamd_session_remove_event (session=0x8199ed020, fin=0x4a94f0 <lua_redis_fin>, ud=0x807042d40)
    at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-c6673ac/src/libserver/events.c:211
        search_ev = {subsystem = 109913728, fin = 0x4a94f0 <lua_redis_fin>, user_data = 0x807042d40, w = 0x800000002}
        found_ev = (struct rspamd_async_event *) 0x819941ed8
#14 0x00000000004a9913 in lua_redis_push_data (r=0x8199070d0, ctx=0x8198531b0, sp_ud=0x807042d40) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-c6673ac/src/lua/lua_redis.c:347
        ud = (struct lua_redis_userdata *) 0x8198531b8
#15 0x00000000004a938d in lua_redis_callback (c=0x8068d2680, r=0x8199070d0, priv=0x807042d40) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-c6673ac/src/lua/lua_redis.c:387
        reply = (redisReply *) 0x8199070d0
        sp_ud = (struct lua_redis_specific_userdata *) 0x807042d40
        ctx = (struct lua_redis_ctx *) 0x8198531b0
        ud = (struct lua_redis_userdata *) 0x8198531b8
        ac = (redisAsyncContext *) 0x7fffffffe250
#16 0x00000000005b9da9 in redisProcessCallbacks (ac=<value optimized out>) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-c6673ac/contrib/hiredis/async.c:271
        c = <value optimized out>
        reply = <value optimized out>
        status = <value optimized out>
#17 0x000000000050f22a in redisLibeventReadEvent (fd=13, event=2, arg=0x80cf3a880) at libevent.h:45
        e = (redisLibeventEvents *) 0x80cf3a880
#18 0x00000008018c5a1f in event_base_assert_ok_nolock_ () from /usr/local/lib/libevent-2.1.so.6
No symbol table info available.
#19 0x00000008018c1cff in event_base_loop () from /usr/local/lib/libevent-2.1.so.6
No symbol table info available.
#20 0x00000000004272d5 in start_worker (worker=0x8071ffe00) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-c6673ac/src/worker.c:648
        ctx = (struct rspamd_worker_ctx *) 0x80691b1b0
#21 0x0000000000508e23 in rspamd_fork_worker (rspamd_main=0x806831000, cf=0x8068b31c0, index=0, ev_base=0x80c7f6f00)
    at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-c6673ac/src/libserver/worker_util.c:606
        wrk = (struct rspamd_worker *) 0x8071ffe00
        rc = 0
        rlim = {rlim_cur = 104857600, rlim_max = 104857600}
#22 0x0000000000426e8a in spawn_worker_type (rspamd_main=0x806831000, ev_base=0x80c7f6f00, cf=0x8068b31c0) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-c6673ac/src/rspamd.c:521
        i = 0
#23 0x0000000000425556 in spawn_workers (rspamd_main=0x806831000, ev_base=0x80c7f6f00) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-c6673ac/src/rspamd.c:594
        cur = (GList *) 0x8068a8540
        ls = (GList *) 0x80709e920
        cf = (struct rspamd_worker_conf *) 0x8068b31c0
        p = 0x0
        key = 14567105553925777530
        bcf = (struct rspamd_worker_bind_conf *) 0x0
        listen_ok = 1
        seen_mandatory_workers = (GPtrArray *) 0x80709e880
        cw = (worker_t **) 0x7fffffffec10
        wrk = (worker_t *) 0x7fffffffebc8
        i = 8
#24 0x0000000000423cc4 in main (argc=1, argv=0x7fffffffebd0, env=0x7fffffffec10) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-c6673ac/src/rspamd.c:1376
        i = 1
        res = 0
        signals = {__sigaction_u = {__sa_handler = 0, __sa_sigaction = 0}, sa_flags = 0, sa_mask = {__bits = 0x7fffffffeb24}}
        sigpipe_act = {__sigaction_u = {__sa_handler = 0x1, __sa_sigaction = 0x1}, sa_flags = 0, sa_mask = {__bits = 0x7fffffffeb04}}
        pworker = (worker_t **) 0x8eedc0
        type = 1
        control_addr = (rspamd_inet_addr_t *) 0x8070940d0
        ev_base = (struct event_base *) 0x80c7f6f00
        term_ev = {ev_evcallback = {evcb_active_next = {tqe_next = 0x8008cd140, tqe_prev = 0x0}, evcb_flags = 128, evcb_pri = 0 '\0', evcb_closure = 1 '\001', evcb_cb_union = {
      evcb_callback = 0x424820 <rspamd_term_handler>, evcb_selfcb = 0x424820 <rspamd_term_handler>, evcb_evfinalize = 0x424820 <rspamd_term_handler>, evcb_cbfinalize = 0x424820 <rspamd_term_handler>},
    evcb_arg = 0x806831000}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0x7fffffffffff, tqe_prev = 0x7fffffffeb00}, min_heap_idx = -1}, ev_fd = 15, ev_base = 0x80c7f6f00, ev_ = {ev_io = {
      ev_io_next = {le_next = 0x0, le_prev = 0x80c7f9048}, ev_timeout = {tv_sec = 0, tv_usec = 0}}, ev_signal = {ev_signal_next = {le_next = 0x0, le_prev = 0x80c7f9048}, ev_ncalls = 0, ev_pncalls = 0x0}},
  ev_events = 24, ev_res = 0, ev_timeout = {tv_sec = 0, tv_usec = 34369122304}}
---Type <return> to continue, or q <return> to quit---
        int_ev = {ev_evcallback = {evcb_active_next = {tqe_next = 0x806816000, tqe_prev = 0x1}, evcb_flags = 128, evcb_pri = 0 '\0', evcb_closure = 1 '\001', evcb_cb_union = {
      evcb_callback = 0x424820 <rspamd_term_handler>, evcb_selfcb = 0x424820 <rspamd_term_handler>, evcb_evfinalize = 0x424820 <rspamd_term_handler>, evcb_cbfinalize = 0x424820 <rspamd_term_handler>},
    evcb_arg = 0x806831000}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0x7fffffffffff, tqe_prev = 0x80379c5f5}, min_heap_idx = -1}, ev_fd = 2, ev_base = 0x80c7f6f00, ev_ = {ev_io = {
      ev_io_next = {le_next = 0x0, le_prev = 0x80c7f9050}, ev_timeout = {tv_sec = 34426257408, tv_usec = 0}}, ev_signal = {ev_signal_next = {le_next = 0x0, le_prev = 0x80c7f9050}, ev_ncalls = 0,
      ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_timeout = {tv_sec = 34371171744, tv_usec = 140737488349952}}
        cld_ev = {ev_evcallback = {evcb_active_next = {tqe_next = 0x0, tqe_prev = 0x0}, evcb_flags = 128, evcb_pri = 0 '\0', evcb_closure = 1 '\001', evcb_cb_union = {
      evcb_callback = 0x424990 <rspamd_cld_handler>, evcb_selfcb = 0x424990 <rspamd_cld_handler>, evcb_evfinalize = 0x424990 <rspamd_cld_handler>, evcb_cbfinalize = 0x424990 <rspamd_cld_handler>},
    evcb_arg = 0x806831000}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0xffffffff, tqe_prev = 0xd7}, min_heap_idx = -1}, ev_fd = 20, ev_base = 0x80c7f6f00, ev_ = {ev_io = {ev_io_next = {
        le_next = 0x0, le_prev = 0x80c7f9060}, ev_timeout = {tv_sec = 0, tv_usec = 0}}, ev_signal = {ev_signal_next = {le_next = 0x0, le_prev = 0x80c7f9060}, ev_ncalls = 0, ev_pncalls = 0x0}},
  ev_events = 24, ev_res = 0, ev_timeout = {tv_sec = 4201224, tv_usec = 1}}
        hup_ev = {ev_evcallback = {evcb_active_next = {tqe_next = 0x8008c8238, tqe_prev = 0x8008c8258}, evcb_flags = 128, evcb_pri = 0 '\0', evcb_closure = 1 '\001', evcb_cb_union = {
      evcb_callback = 0x4248c0 <rspamd_hup_handler>, evcb_selfcb = 0x4248c0 <rspamd_hup_handler>, evcb_evfinalize = 0x4248c0 <rspamd_hup_handler>, evcb_cbfinalize = 0x4248c0 <rspamd_hup_handler>},
    evcb_arg = 0x806831000}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0xffffffff, tqe_prev = 0x0}, min_heap_idx = -1}, ev_fd = 1, ev_base = 0x80c7f6f00, ev_ = {ev_io = {ev_io_next = {
        le_next = 0x0, le_prev = 0x80c7f9058}, ev_timeout = {tv_sec = 4194304, tv_usec = 0}}, ev_signal = {ev_signal_next = {le_next = 0x0, le_prev = 0x80c7f9058}, ev_ncalls = 0, ev_pncalls = 0x0}},
  ev_events = 24, ev_res = 0, ev_timeout = {tv_sec = 34369151024, tv_usec = 1}}
        usr1_ev = {ev_evcallback = {evcb_active_next = {tqe_next = 0x8008ee400, tqe_prev = 0x8008ee800}, evcb_flags = 128, evcb_pri = 0 '\0', evcb_closure = 1 '\001', evcb_cb_union = {
      evcb_callback = 0x424eb0 <rspamd_usr1_handler>, evcb_selfcb = 0x424eb0 <rspamd_usr1_handler>, evcb_evfinalize = 0x424eb0 <rspamd_usr1_handler>, evcb_cbfinalize = 0x424eb0 <rspamd_usr1_handler>},
    evcb_arg = 0x806831000}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0x8ffffffff, tqe_prev = 0x8008f1c00}, min_heap_idx = -1}, ev_fd = 30, ev_base = 0x80c7f6f00, ev_ = {ev_io = {
      ev_io_next = {le_next = 0x0, le_prev = 0x80c7f9068}, ev_timeout = {tv_sec = 34369110016, tv_usec = 0}}, ev_signal = {ev_signal_next = {le_next = 0x0, le_prev = 0x80c7f9068}, ev_ncalls = 0,
      ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_timeout = {tv_sec = 34359738371, tv_usec = 32}}
        control_ev = {ev_evcallback = {evcb_active_next = {tqe_next = 0x0, tqe_prev = 0x7fffffffe9e8}, evcb_flags = 10157, evcb_pri = 0 '\0', evcb_closure = 0 '\0', evcb_cb_union = {
      evcb_callback = 0x8008ea000, evcb_selfcb = 0x8008ea000, evcb_evfinalize = 0x8008ea000, evcb_cbfinalize = 0x8008ea000}, evcb_arg = 0x8008ea000}, ev_timeout_pos = {ev_next_with_common_timeout = {
      tqe_next = 0x7fffffffe9a0, tqe_prev = 0x8008cd759}, min_heap_idx = -5728}, ev_fd = 9347072, ev_base = 0x8008ea400, ev_ = {ev_io = {ev_io_next = {le_next = 0x8008ea800, le_prev = 0x8008eac00},
      ev_timeout = {tv_sec = 34369097728, tv_usec = 34369098752}}, ev_signal = {ev_signal_next = {le_next = 0x8008ea800, le_prev = 0x8008eac00}, ev_ncalls = -12288, ev_pncalls = 0x8008ed400}},
  ev_events = -10240, ev_res = 142, ev_timeout = {tv_sec = 34369100800, tv_usec = 34369101824}}
        term_tv = {tv_sec = 34425120288, tv_usec = 140737488349800}
        rspamd_main = (struct rspamd_main *) 0x806831000
Current language:  auto; currently minimal
(gdb) q
```

**Comment by moisseev** [comment]
Fixed with f6bcc7cd0937d1d4657f815d5d00f2aed7228dd9
