### ISSUE TITLE
Ubuntu 16.04 stable seqfault

### ISSUE THREAD

**Issue by pcopfer** [vstakhov/rspamd#1679]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
```
apt show rspamd
Package: rspamd
Version: 1.6.0-1~xenial
Priority: extra
Maintainer: Vsevolod Stakhov <vsevolod@highsecure.ru>
Installed-Size: 35.7 MB
Depends: adduser, lsb-base, ca-certificates, init-system-helpers (>= 1.18~), libc6 (>= 2.17), libevent-2.0-5 (>= 2.0.10-stable), libfann2 (>= 2.1.0~beta~dfsg), libgcc1 (>= 1:3.3), libgd3 (>= 2.1.0~alpha~), libglib2.0-0 (>= 2.39.4), libicu55 (>= 55.1-1~), libjemalloc1 (>= 2.1.1), libmagic1 (>= 5.12), libpcre3, libsqlite3-0 (>= 3.7.15), libssl1.0.0 (>= 1.0.1), libstdc++6 (>= 5.2)
Download-Size: 9,242 kB
APT-Manual-Installed: yes
APT-Sources: http://rspamd.com/apt-stable xenial/main amd64 Packages
```
### Operation system, CPU, memory and environment:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

libivrt-vm
2 GB memory
```

### Description (Please provide a descriptive summary of the issue):

Problem started after upgrade to actual version and remove rmilter. To fix, purge package, same problem. Constant seqfault.

Jun 13 20:51:55 XXX kernel: rspamd[6931]: segfault at 59 ip 00000000005338db sp 00007ffe79e80d30 error 4 in rspamd[400000+a8a000]

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):
```
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/rspamd...Reading symbols from /usr/lib/debug/.build-id/da/61370504cf45a1ba30851916c41f72d51e4fc8.debug...done.
done.
[New LWP 5914]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `rspamd: rspamd_proxy process                 '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  rdns_make_request_full (resolver=0x0, cb=0x487370 <rspamd_monitored_dns_cb>, cbdata=0x7f668dddd8b0, timeout=1, repeats=5, queries=1) at /rspamd-1.6.0/contrib/librdns/resolver.c:533
533	/rspamd-1.6.0/contrib/librdns/resolver.c: No such file or directory.
(gdb) bt full
#0  rdns_make_request_full (resolver=0x0, cb=0x487370 <rspamd_monitored_dns_cb>, cbdata=0x7f668dddd8b0, timeout=1, repeats=5, queries=1) at /rspamd-1.6.0/contrib/librdns/resolver.c:533
        args = <error reading variable args (Attempt to dereference a generic pointer.)>
        req = <optimized out>
        serv = <optimized out>
        r = <optimized out>
        type = <optimized out>
        i = <optimized out>
        tlen = 0
        clen = 0
        cur = <optimized out>
        olen = 140078441760824
        cur_name = <optimized out>
        last_name = 0x0
        comp = 0x7f668de46900
        __func__ = "rdns_make_request_full"
#1  0x0000000000486b17 in rspamd_monitored_dns_mon (m=0x7f668ddd1190, ctx=<optimized out>, ud=0x7f668dddd8b0) at /rspamd-1.6.0/src/libserver/monitored.c:308
        conf = 0x7f668dddd8b0
        __func__ = "rspamd_monitored_dns_mon"
#2  0x000000000048646d in rspamd_monitored_periodic (fd=<optimized out>, what=<optimized out>, ud=0x7f668ddd1190) at /rspamd-1.6.0/src/libserver/monitored.c:136
        m = 0x7f668ddd1190
        tv = {tv_sec = 72, tv_usec = 566519}
        jittered = <optimized out>
#3  0x00007f66940b04c9 in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
No symbol table info available.
#4  0x00000000004fbbff in start_rspamd_proxy (worker=0x7f668de8bf00) at /rspamd-1.6.0/src/rspamd_proxy.c:2046
        ctx = 0x7f668dd4bb68
        rot_tv = {tv_sec = 88, tv_usec = 0}
#5  0x00000000004aba43 in rspamd_fork_worker (rspamd_main=0x7f668dc64080, cf=0x7f668dc43960, index=0, ev_base=<optimized out>) at /rspamd-1.6.0/src/libserver/worker_util.c:606
        wrk = 0x7f668de8bf00
        rc = <optimized out>
        rlim = {rlim_cur = 104857600, rlim_max = 104857600}
        __func__ = "rspamd_fork_worker"
#6  0x00000000004fcad6 in rspamd_fork_delayed_cb (signo=<optimized out>, what=<optimized out>, arg=0x7f668dc2f520) at /rspamd-1.6.0/src/rspamd.c:325
---Type <return> to continue, or q <return> to quit---
        w = 0x7f668dc2f520
#7  0x00007f66940b04c9 in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
No symbol table info available.
#8  0x000000000043d66a in main (argc=1, argv=0x7ffe79e81778, env=<optimized out>) at /rspamd-1.6.0/src/rspamd.c:1392
        i = <optimized out>
        res = 0
        signals = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = 0, sa_restorer = 0x0}
        sigpipe_act = {__sigaction_handler = {sa_handler = 0x1, sa_sigaction = 0x1}, sa_mask = {__val = {4096, 0 <repeats 15 times>}}, sa_flags = 0, sa_restorer = 0x0}
        pworker = <optimized out>
        type = <optimized out>
        control_addr = 0x7f668de5cc10
        ev_base = 0x7f668dcadd00
        term_ev = {ev_active_next = {tqe_next = 0x0, tqe_prev = 0x3b3}, ev_next = {tqe_next = 0x7ffe79e81400, tqe_prev = 0x7f668dcade60}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0x7f66ffffffff, tqe_prev = 0x7ffe79e814f0}, min_heap_idx = -1}, 
          ev_fd = 15, ev_base = 0x7f668dcadd00, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x7f66877480d0}, ev_timeout = {tv_sec = 4294901760, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x7f66877480d0}, ev_ncalls = 0, 
              ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, ev_pri = 0 '\000', ev_closure = 1 '\001', ev_timeout = {tv_sec = 140078579295464, tv_usec = 4}, ev_callback = 0x4fc5c0 <rspamd_term_handler>, ev_arg = 0x7f668dc64080}
        int_ev = {ev_active_next = {tqe_next = 0x26, tqe_prev = 0x7f6695f5b9e8}, ev_next = {tqe_next = 0x7ffe79e812e0, tqe_prev = 0x7f668dcade60}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0x1ffffffff, tqe_prev = 0x7f6695f684c0}, min_heap_idx = -1}, 
          ev_fd = 2, ev_base = 0x7f668dcadd00, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x7f6687748100}, ev_timeout = {tv_sec = 140730943668224, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x7f6687748100}, ev_ncalls = 0, 
              ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, ev_pri = 0 '\000', ev_closure = 1 '\001', ev_timeout = {tv_sec = 140078579249888, tv_usec = 1}, ev_callback = 0x4fc5c0 <rspamd_term_handler>, ev_arg = 0x7f668dc64080}
        cld_ev = {ev_active_next = {tqe_next = 0x0, tqe_prev = 0x7f6687748110}, ev_next = {tqe_next = 0x7ffe79e81250, tqe_prev = 0x7f668dcade60}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0xffffffff, tqe_prev = 0x419523}, min_heap_idx = -1}, 
          ev_fd = 17, ev_base = 0x7f668dcadd00, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x7f66877480f0}, ev_timeout = {tv_sec = 0, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x7f66877480f0}, ev_ncalls = 0, 
              ev_pncalls = 0x0}}, ev_events = 24, ev_res = 8, ev_flags = 128, ev_pri = 0 '\000', ev_closure = 1 '\001', ev_timeout = {tv_sec = 140078557441408, tv_usec = 140730943673364}, ev_callback = 0x4fc620 <rspamd_cld_handler>, ev_arg = 0x7f668dc64080}
        hup_ev = {ev_active_next = {tqe_next = 0x53, tqe_prev = 0x7f6695b0ab08}, ev_next = {tqe_next = 0x7ffe79e81370, tqe_prev = 0x7f668dcade60}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0x7ffeffffffff, tqe_prev = 0x7f6695d4ae11 <do_lookup_x+369>}, 
            min_heap_idx = -1}, ev_fd = 1, ev_base = 0x7f668dcadd00, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x7f66877480c0}, ev_timeout = {tv_sec = 221839360, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x7f66877480c0}, 
              ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, ev_pri = 0 '\000', ev_closure = 1 '\001', ev_timeout = {tv_sec = 140078557441408, tv_usec = 140078557495288}, ev_callback = 0x4fd510 <rspamd_hup_handler>, 
          ev_arg = 0x7f668dc64080}
        usr1_ev = {ev_active_next = {tqe_next = 0x0, tqe_prev = 0x7f669456d0cc}, ev_next = {tqe_next = 0x7f668de8be58, tqe_prev = 0x7f668dcade60}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0xffffffff, tqe_prev = 0xb92f1b <fillLimits+1115>}, 
            min_heap_idx = -1}, ev_fd = 10, ev_base = 0x7f668dcadd00, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x7f66877480e0}, ev_timeout = {tv_sec = 140078579253248, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, 
                tqe_prev = 0x7f66877480e0}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, ev_pri = 0 '\000', ev_closure = 1 '\001', ev_timeout = {tv_sec = 83, tv_usec = 140078579340624}, ev_callback = 0x4fc9b0 <rspamd_usr1_handler>, 
          ev_arg = 0x7f668dc64080}
        control_ev = {ev_active_next = {tqe_next = 0x7ffe79f4a2b0, tqe_prev = 0x7ffe79f4a1a8}, ev_next = {tqe_next = 0x7f668de8bb58, tqe_prev = 0x7f668dcade60}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0x7f66ffffffff, 
              tqe_prev = 0x7f6695d4ab70 <check_match+112>}, min_heap_idx = -1}, ev_fd = 5, ev_base = 0x7f668dcadd00, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x7f668772daa0}, ev_timeout = {tv_sec = 0, tv_usec = 0}}, ev_signal = {ev_signal_next = {
                tqe_next = 0x0, tqe_prev = 0x7f668772daa0}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 18, ev_res = 0, ev_flags = 128, ev_pri = 0 '\000', ev_closure = 2 '\002', ev_timeout = {tv_sec = 140078574775048, tv_usec = 140078579340624}, 
          ev_callback = 0x4fc9e0 <rspamd_control_handler>, ev_arg = 0x7f668dc64080}
---Type <return> to continue, or q <return> to quit---
        term_tv = {tv_sec = 140076063391744, tv_usec = 140730943673056}
        __func__ = "main"
```
### Configuration:
local.d/
- options.inc
```
cores_dir = "/coreland/";
max_cores_size = 1G;
```
- worker-proxy.inc
```
# local.d/worker-proxy.inc
milter = yes; # Enable milter mode
timeout = 120s; # Needed for Milter usually
upstream "local" {
  default = yes; # Self-scan upstreams are always default
  self_scan = yes; # Enable self-scan
}
```

### Additional information:
- postfix as MTA
- /rspamd-1.6.0/contrib/librdns/resolver.c: No such file or directory. ?

**Comment by vstakhov** [comment]
You have some issues with your DNS server configuration. Please configure as it is described in the documentation. I agree that Rspamd should not segfault in this case...

**Comment by pcopfer** [comment]
Add to local.d/options.inc stop the segfault.
```
dns {
		nameserver = "master-slave:127.0.0.1:53:10,8.8.8.8:53:1";
	}
```

**Comment by vstakhov** [comment]
I have added a workaround for the crash.
