### ISSUE TITLE
core dumped signal 6 and 11

### ISSUE THREAD

**Issue by scubasound** [vstakhov/rspamd#2004]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [] Always
* [X] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5 Branch rspamd-1.6#2000 2018-01-23 (9181480ae07f74992f60845da849d841a6cde7e9)
### Operation system, CPU, memory and environment:
11.1-RELEASE-p6
### Description (Please provide a descriptive summary of the issue):
Sporadic daily crashes of rspamd-proxy
### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):

# gdb /usr/local/bin/rspamd -c /tmp/rspamd-1.6.5-49662.core
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...(no debugging symbols found)...

warning: core file may not match specified executable file.
Core was generated by `rspamd: rspamd_proxy process'.
Program terminated with signal 6, Aborted.
Reading symbols from /usr/local/lib/libfann.so.2...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libfann.so.2
Reading symbols from /lib/libutil.so.9...Reading symbols from /usr/lib/debug//lib/libutil.so.9.debug...done.
done.
Loaded symbols for /lib/libutil.so.9
Reading symbols from /usr/local/lib/libgthread-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libgthread-2.0.so.0
Reading symbols from /usr/local/lib/libglib-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libglib-2.0.so.0
Reading symbols from /usr/local/lib/libintl.so.8...done.
Loaded symbols for /usr/local/lib/libintl.so.8
Reading symbols from /usr/local/lib/libpcre.so.1...done.
Loaded symbols for /usr/local/lib/libpcre.so.1
Reading symbols from /usr/local/lib/libevent-2.1.so.6...done.
Loaded symbols for /usr/local/lib/libevent-2.1.so.6
Reading symbols from /usr/local/lib/libsqlite3.so.0...done.
Loaded symbols for /usr/local/lib/libsqlite3.so.0
Reading symbols from /usr/local/lib/libicui18n.so.60...done.
Loaded symbols for /usr/local/lib/libicui18n.so.60
Reading symbols from /usr/local/lib/libicuuc.so.60...done.
Loaded symbols for /usr/local/lib/libicuuc.so.60
Reading symbols from /usr/local/lib/libicudata.so.60...
warning: Lowest section in /usr/local/lib/libicudata.so.60 is .hash at 0000000000000120
done.
Loaded symbols for /usr/local/lib/libicudata.so.60
Reading symbols from /lib/libcrypto.so.8...Reading symbols from /usr/lib/debug//lib/libcrypto.so.8.debug...done.
done.
Loaded symbols for /lib/libcrypto.so.8
Reading symbols from /usr/lib/libssl.so.8...Reading symbols from /usr/lib/debug//usr/lib/libssl.so.8.debug...done.
done.
Loaded symbols for /usr/lib/libssl.so.8
Reading symbols from /usr/lib/libmagic.so.4...Reading symbols from /usr/lib/debug//usr/lib/libmagic.so.4.debug...done.
done.
Loaded symbols for /usr/lib/libmagic.so.4
Reading symbols from /lib/libm.so.5...Reading symbols from /usr/lib/debug//lib/libm.so.5.debug...done.
done.
Loaded symbols for /lib/libm.so.5
Reading symbols from /usr/local/lib/libgd.so.6...done.
Loaded symbols for /usr/local/lib/libgd.so.6
Reading symbols from /lib/libthr.so.3...Reading symbols from /usr/lib/debug//lib/libthr.so.3.debug...done.
done.
Loaded symbols for /lib/libthr.so.3
Reading symbols from /usr/local/lib/libluajit-5.1.so.2...done.
Loaded symbols for /usr/local/lib/libluajit-5.1.so.2
Reading symbols from /usr/local/lib/rspamd/librspamd-actrie.so...done.
Loaded symbols for /usr/local/lib/rspamd/librspamd-actrie.so
Reading symbols from /lib/libc.so.7...Reading symbols from /usr/lib/debug//lib/libc.so.7.debug...done.
done.
Loaded symbols for /lib/libc.so.7
Reading symbols from /usr/local/lib/libiconv.so.2...done.
Loaded symbols for /usr/local/lib/libiconv.so.2
Reading symbols from /usr/lib/libc++.so.1...Reading symbols from /usr/lib/debug//usr/lib/libc++.so.1.debug...done.
done.
Loaded symbols for /usr/lib/libc++.so.1
Reading symbols from /lib/libcxxrt.so.1...Reading symbols from /usr/lib/debug//lib/libcxxrt.so.1.debug...done.
done.
Loaded symbols for /lib/libcxxrt.so.1
Reading symbols from /lib/libgcc_s.so.1...Reading symbols from /usr/lib/debug//lib/libgcc_s.so.1.debug...done.
done.
Loaded symbols for /lib/libgcc_s.so.1
Reading symbols from /lib/libz.so.6...Reading symbols from /usr/lib/debug//lib/libz.so.6.debug...done.
done.
Loaded symbols for /lib/libz.so.6
Reading symbols from /usr/local/lib/libpng16.so.16...done.
Loaded symbols for /usr/local/lib/libpng16.so.16
Reading symbols from /usr/local/lib/libfontconfig.so.1...done.
Loaded symbols for /usr/local/lib/libfontconfig.so.1
Reading symbols from /usr/local/lib/libfreetype.so.6...done.
Loaded symbols for /usr/local/lib/libfreetype.so.6
Reading symbols from /usr/local/lib/libjpeg.so.8...done.
Loaded symbols for /usr/local/lib/libjpeg.so.8
Reading symbols from /usr/local/lib/libtiff.so.5...done.
Loaded symbols for /usr/local/lib/libtiff.so.5
Reading symbols from /usr/local/lib/libwebp.so.7...done.
Loaded symbols for /usr/local/lib/libwebp.so.7
Reading symbols from /usr/local/lib/libexpat.so.1...done.
Loaded symbols for /usr/local/lib/libexpat.so.1
Reading symbols from /usr/lib/libbz2.so.4...Reading symbols from /usr/lib/debug//usr/lib/libbz2.so.4.debug...done.
done.
Loaded symbols for /usr/lib/libbz2.so.4
Reading symbols from /usr/lib/liblzma.so.5...Reading symbols from /usr/lib/debug//usr/lib/liblzma.so.5.debug...done.
done.
Loaded symbols for /usr/lib/liblzma.so.5
Reading symbols from /usr/local/lib/libjbig.so.2...done.
Loaded symbols for /usr/local/lib/libjbig.so.2
Reading symbols from /libexec/ld-elf.so.1...Reading symbols from /usr/lib/debug//libexec/ld-elf.so.1.debug...done.
done.
Loaded symbols for /libexec/ld-elf.so.1
#0  0x0000000803eff84a in thr_kill () from /lib/libc.so.7
(gdb) bt full
#0  0x0000000803eff84a in thr_kill () from /lib/libc.so.7
No symbol table info available.
#1  0x0000000803eff814 in __raise (s=6) at /usr/src/lib/libc/gen/raise.c:52
	id = <value optimized out>
#2  0x0000000803eff789 in abort () at /usr/src/lib/libc/stdlib/abort.c:65
	act = <value optimized out>
#3  0x000000080182af41 in event_logv_ () from /usr/local/lib/libevent-2.1.so.6
No symbol table info available.
#4  0x000000080182b1e9 in event_errx () from /usr/local/lib/libevent-2.1.so.6
No symbol table info available.
#5  0x0000000801825fd9 in event_changelist_remove_all_ ()
   from /usr/local/lib/libevent-2.1.so.6
No symbol table info available.
#6  0x000000080182c34d in event_set_log_callback ()
   from /usr/local/lib/libevent-2.1.so.6
No symbol table info available.
#7  0x0000000801820d98 in event_base_loop ()
   from /usr/local/lib/libevent-2.1.so.6
No symbol table info available.
#8  0x0000000000420f94 in rspamd_worker_guard_handler ()
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#9  0x00000000004b68de in rspamd_urls_cmp ()
No symbol table info available.
#10 0x000000000041f9f0 in ?? ()
No symbol table info available.
#11 0x000000000041f245 in ?? ()
No symbol table info available.
#12 0x0000000801824e14 in event_base_assert_ok_nolock_ ()
   from /usr/local/lib/libevent-2.1.so.6
No symbol table info available.
#13 0x0000000801820f4e in event_base_loop ()
   from /usr/local/lib/libevent-2.1.so.6
No symbol table info available.
#14 0x000000000041dcc2 in ?? ()
No symbol table info available.
#15 0x00000000004115bf in ?? ()
No symbol table info available.
#16 0x0000000800843000 in ?? ()
No symbol table info available.
#17 0x0000000000000000 in ?? ()
No symbol table info available.
(gdb) 

=====================================
# gdb /usr/local/bin/rspamd -c /tmp/rspamd-1.6.5-51009.core 
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...(no debugging symbols found)...

warning: core file may not match specified executable file.
Core was generated by `rspamd: rspamd_proxy process'.
Program terminated with signal 11, Segmentation fault.
Reading symbols from /usr/local/lib/libfann.so.2...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libfann.so.2
Reading symbols from /lib/libutil.so.9...Reading symbols from /usr/lib/debug//lib/libutil.so.9.debug...done.
done.
Loaded symbols for /lib/libutil.so.9
Reading symbols from /usr/local/lib/libgthread-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libgthread-2.0.so.0
Reading symbols from /usr/local/lib/libglib-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libglib-2.0.so.0
Reading symbols from /usr/local/lib/libintl.so.8...done.
Loaded symbols for /usr/local/lib/libintl.so.8
Reading symbols from /usr/local/lib/libpcre.so.1...done.
Loaded symbols for /usr/local/lib/libpcre.so.1
Reading symbols from /usr/local/lib/libevent-2.1.so.6...done.
Loaded symbols for /usr/local/lib/libevent-2.1.so.6
Reading symbols from /usr/local/lib/libsqlite3.so.0...done.
Loaded symbols for /usr/local/lib/libsqlite3.so.0
Reading symbols from /usr/local/lib/libicui18n.so.60...done.
Loaded symbols for /usr/local/lib/libicui18n.so.60
Reading symbols from /usr/local/lib/libicuuc.so.60...done.
Loaded symbols for /usr/local/lib/libicuuc.so.60
Reading symbols from /usr/local/lib/libicudata.so.60...
warning: Lowest section in /usr/local/lib/libicudata.so.60 is .hash at 0000000000000120
done.
Loaded symbols for /usr/local/lib/libicudata.so.60
Reading symbols from /lib/libcrypto.so.8...Reading symbols from /usr/lib/debug//lib/libcrypto.so.8.debug...done.
done.
Loaded symbols for /lib/libcrypto.so.8
Reading symbols from /usr/lib/libssl.so.8...Reading symbols from /usr/lib/debug//usr/lib/libssl.so.8.debug...done.
done.
Loaded symbols for /usr/lib/libssl.so.8
Reading symbols from /usr/lib/libmagic.so.4...Reading symbols from /usr/lib/debug//usr/lib/libmagic.so.4.debug...done.
done.
Loaded symbols for /usr/lib/libmagic.so.4
Reading symbols from /lib/libm.so.5...Reading symbols from /usr/lib/debug//lib/libm.so.5.debug...done.
done.
Loaded symbols for /lib/libm.so.5
Reading symbols from /usr/local/lib/libgd.so.6...done.
Loaded symbols for /usr/local/lib/libgd.so.6
Reading symbols from /lib/libthr.so.3...Reading symbols from /usr/lib/debug//lib/libthr.so.3.debug...done.
done.
Loaded symbols for /lib/libthr.so.3
Reading symbols from /usr/local/lib/libluajit-5.1.so.2...done.
Loaded symbols for /usr/local/lib/libluajit-5.1.so.2
Reading symbols from /usr/local/lib/rspamd/librspamd-actrie.so...done.
Loaded symbols for /usr/local/lib/rspamd/librspamd-actrie.so
Reading symbols from /lib/libc.so.7...Reading symbols from /usr/lib/debug//lib/libc.so.7.debug...done.
done.
Loaded symbols for /lib/libc.so.7
Reading symbols from /usr/local/lib/libiconv.so.2...done.
Loaded symbols for /usr/local/lib/libiconv.so.2
Reading symbols from /usr/lib/libc++.so.1...Reading symbols from /usr/lib/debug//usr/lib/libc++.so.1.debug...done.
done.
Loaded symbols for /usr/lib/libc++.so.1
Reading symbols from /lib/libcxxrt.so.1...Reading symbols from /usr/lib/debug//lib/libcxxrt.so.1.debug...done.
done.
Loaded symbols for /lib/libcxxrt.so.1
Reading symbols from /lib/libgcc_s.so.1...Reading symbols from /usr/lib/debug//lib/libgcc_s.so.1.debug...done.
done.
Loaded symbols for /lib/libgcc_s.so.1
Reading symbols from /lib/libz.so.6...Reading symbols from /usr/lib/debug//lib/libz.so.6.debug...done.
done.
Loaded symbols for /lib/libz.so.6
Reading symbols from /usr/local/lib/libpng16.so.16...done.
Loaded symbols for /usr/local/lib/libpng16.so.16
Reading symbols from /usr/local/lib/libfontconfig.so.1...done.
Loaded symbols for /usr/local/lib/libfontconfig.so.1
Reading symbols from /usr/local/lib/libfreetype.so.6...done.
Loaded symbols for /usr/local/lib/libfreetype.so.6
Reading symbols from /usr/local/lib/libjpeg.so.8...done.
Loaded symbols for /usr/local/lib/libjpeg.so.8
Reading symbols from /usr/local/lib/libtiff.so.5...done.
Loaded symbols for /usr/local/lib/libtiff.so.5
Reading symbols from /usr/local/lib/libwebp.so.7...done.
Loaded symbols for /usr/local/lib/libwebp.so.7
Reading symbols from /usr/local/lib/libexpat.so.1...done.
Loaded symbols for /usr/local/lib/libexpat.so.1
Reading symbols from /usr/lib/libbz2.so.4...Reading symbols from /usr/lib/debug//usr/lib/libbz2.so.4.debug...done.
done.
Loaded symbols for /usr/lib/libbz2.so.4
Reading symbols from /usr/lib/liblzma.so.5...Reading symbols from /usr/lib/debug//usr/lib/liblzma.so.5.debug...done.
done.
Loaded symbols for /usr/lib/liblzma.so.5
Reading symbols from /usr/local/lib/libjbig.so.2...done.
Loaded symbols for /usr/local/lib/libjbig.so.2
Reading symbols from /libexec/ld-elf.so.1...Reading symbols from /usr/lib/debug//libexec/ld-elf.so.1.debug...done.
done.
Loaded symbols for /libexec/ld-elf.so.1
#0  0x0000000801825a79 in evmap_io_active_ ()
   from /usr/local/lib/libevent-2.1.so.6
(gdb) bt full
#0  0x0000000801825a79 in evmap_io_active_ ()
   from /usr/local/lib/libevent-2.1.so.6
No symbol table info available.
#1  0x000000080182c52b in event_set_log_callback ()
   from /usr/local/lib/libevent-2.1.so.6
No symbol table info available.
#2  0x0000000801820d98 in event_base_loop ()
   from /usr/local/lib/libevent-2.1.so.6
No symbol table info available.
#3  0x0000000000420f94 in rspamd_worker_guard_handler ()
No symbol table info available.
#4  0x00000000004b68de in rspamd_urls_cmp ()
No symbol table info available.
#5  0x000000000041f8cb in ?? ()
No symbol table info available.
#6  0x0000000801824da0 in event_base_assert_ok_nolock_ ()
   from /usr/local/lib/libevent-2.1.so.6
No symbol table info available.
#7  0x0000000801820f4e in event_base_loop ()
   from /usr/local/lib/libevent-2.1.so.6
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#8  0x000000000041dcc2 in ?? ()
No symbol table info available.
#9  0x00000000004115bf in ?? ()
No symbol table info available.
#10 0x0000000800843000 in ?? ()
No symbol table info available.
#11 0x0000000000000000 in ?? ()
No symbol table info available.
(gdb) 
### Configuration:
MTA: sendmail 8.15.2

**Comment by scubasound** [comment]
Here is another signal 11 from earlier today:
https://pastebin.com/cVQUfbey

**Comment by scubasound** [comment]
another one exited signal 10 today:
https://pastebin.com/K7PxTHCj

**Comment by scubasound** [comment]
I am pleased to report that after updating to the latest 1.6 Branch #2012 b75c5e7e2f7138f6a736ce5cacdaccb07d10ea34 
and running for 4 days, I no longer see any crashes on sendmail or postfix.
I'm closing the ticket.
