### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rspamd#2332]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [x] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

```
# rspamd -v
Rspamd daemon version 1.7.8-git.a444ae8
```

### Operation system, CPU, memory and environment:

```
# uname -mrs
FreeBSD 11.2-RELEASE amd64
```

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):

```
2018-07-10 14:24:56 #63248(rspamd_proxy) <fcc8da>; lua; settings.lua:335: check for settings
2018-07-10 14:24:56 #63248(rspamd_proxy) <a36f5b>; proxy; rspamd_message_parse: loaded message; id: <e38282df-d7b9-8bfa-4824-55d2f661e2a4@se116.ru>; queue-id: <8EA433A6CF>; size: 3183; checksum: <87df07353859e5f2fb1324768ab7350e>
2018-07-10 14:24:56 #63248(rspamd_proxy) <a36f5b>; lua; settings.lua:335: check for settings
2018-07-10 14:24:56 #63248(rspamd_proxy) <a36f5b>; proxy; rspamd_mime_part_detect_language: detected part language: bg
2018-07-10 14:24:56 #63248(rspamd_proxy) <a36f5b>; proxy; rspamd_mime_part_detect_language: detected part language: en
2018-07-10 14:24:56 #63248(rspamd_proxy) <fcc8da>; proxy; rspamd_mime_part_detect_language: detected part language: bg
2018-07-10 14:24:56 #63248(rspamd_proxy) <fcc8da>; proxy; rspamd_mime_part_detect_language: detected part language: en
2018-07-10 14:24:56 #63248(rspamd_proxy) <a36f5b>; proxy; dkim_module_key_handler: cannot get key for domain dkim._domainkey.se116.ru: dns request to dkim._domainkey.se116.ru failed: no records with this name
2018-07-10 14:24:56 #63248(rspamd_proxy) <fcc8da>; proxy; dkim_module_key_handler: cannot get key for domain dkim._domainkey.se116.ru: dns request to dkim._domainkey.se116.ru failed: no records with this name
2018-07-10 14:24:57 #63248(rspamd_proxy) <a36f5b>; proxy; fuzzy_generate_commands: <e38282df-d7b9-8bfa-4824-55d2f661e2a4@se116.ru>, part is shorter than 1000 bytes: 332 (166 * 2.00 bytes), use direct hash
2018-07-10 14:24:57 #63248(rspamd_proxy) rspamd_crash_sig_handler: caught fatal signal 11(Segmentation fault), pid: 63248, trace:
2018-07-10 14:24:57 #37940(main) <1f4f8a>; main; rspamd_cld_handler: catch SIGCHLD signal, finding terminated workers
2018-07-10 14:24:57 #37940(main) <1f4f8a>; main; rspamd_cld_handler: rspamd_proxy process 63248 terminated abnormally by signal: Segmentation fault and created core file
```

```cxx
# gdb `which rspamd` -c /coreland/rspamd-1.7.8.core
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...

warning: core file may not match specified executable file.
Core was generated by `rspamd: rspamd_proxy process (localhost:11332)'.
Program terminated with signal 11, Segmentation fault.
Reading symbols from /usr/local/lib/libhs.so.4...done.
Loaded symbols for /usr/local/lib/libhs.so.4
Reading symbols from /lib/libutil.so.9...done.
Loaded symbols for /lib/libutil.so.9
Reading symbols from /usr/local/lib/libgthread-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libgthread-2.0.so.0
Reading symbols from /usr/local/lib/libglib-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libglib-2.0.so.0
Reading symbols from /usr/local/lib/libintl.so.8...done.
Loaded symbols for /usr/local/lib/libintl.so.8
Reading symbols from /usr/local/lib/libpcre.so.1...done.
Loaded symbols for /usr/local/lib/libpcre.so.1
Reading symbols from /usr/local/lib/libevent-2.1.so.6...done.
Loaded symbols for /usr/local/lib/libevent-2.1.so.6
Reading symbols from /usr/local/lib/libsqlite3.so.0...done.
Loaded symbols for /usr/local/lib/libsqlite3.so.0
Reading symbols from /usr/local/lib/libicui18n.so.62...done.
Loaded symbols for /usr/local/lib/libicui18n.so.62
Reading symbols from /usr/local/lib/libicuuc.so.62...done.
Loaded symbols for /usr/local/lib/libicuuc.so.62
Reading symbols from /usr/local/lib/libicudata.so.62...
warning: Lowest section in /usr/local/lib/libicudata.so.62 is .hash at 0000000000000120
done.
Loaded symbols for /usr/local/lib/libicudata.so.62
Reading symbols from /lib/libcrypto.so.8...done.
Loaded symbols for /lib/libcrypto.so.8
Reading symbols from /usr/lib/libssl.so.8...done.
Loaded symbols for /usr/lib/libssl.so.8
Reading symbols from /usr/lib/libmagic.so.4...done.
Loaded symbols for /usr/lib/libmagic.so.4
Reading symbols from /lib/libz.so.6...done.
Loaded symbols for /lib/libz.so.6
Reading symbols from /lib/libthr.so.3...done.
Loaded symbols for /lib/libthr.so.3
Reading symbols from /lib/libm.so.5...done.
Loaded symbols for /lib/libm.so.5
Reading symbols from /usr/local/lib/rspamd/librspamd-actrie.so...done.
Loaded symbols for /usr/local/lib/rspamd/librspamd-actrie.so
Reading symbols from /usr/local/lib/libluajit-5.1.so.2...done.
Loaded symbols for /usr/local/lib/libluajit-5.1.so.2
Reading symbols from /lib/libc.so.7...done.
Loaded symbols for /lib/libc.so.7
Reading symbols from /usr/lib/libc++.so.1...done.
Loaded symbols for /usr/lib/libc++.so.1
Reading symbols from /lib/libcxxrt.so.1...done.
Loaded symbols for /lib/libcxxrt.so.1
Reading symbols from /lib/libgcc_s.so.1...done.
Loaded symbols for /lib/libgcc_s.so.1
Reading symbols from /usr/local/lib/libiconv.so.2...done.
Loaded symbols for /usr/local/lib/libiconv.so.2
Reading symbols from /libexec/ld-elf.so.1...done.
Loaded symbols for /libexec/ld-elf.so.1
#0  0x0000000804551916 in memcpy () from /lib/libc.so.7
(gdb) bt full
#0  0x0000000804551916 in memcpy () from /lib/libc.so.7
No symbol table info available.
#1  0x0000000000573d3d in fuzzy_cmd_from_text_part (task=0x8086b6700, rule=0x8070ef7a0, c=0, flag=0, weight=0, short_text=0, pool=0x8093ceaf0, part=0x8097b2090)
    at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-a444ae8/src/plugins/fuzzy_check.c:1396
        shcmd = (struct rspamd_fuzzy_shingle_cmd *) 0x809506434
        cmd = (struct rspamd_fuzzy_cmd *) 0x0
        encshcmd = (struct rspamd_fuzzy_encrypted_shingle_cmd *) 0x8095063e0
        enccmd = (struct rspamd_fuzzy_encrypted_cmd *) 0x0
        cached = (struct rspamd_cached_shingles *) 0x809506160
        sh = (struct rspamd_shingle *) 0x0
        i = 0
        st = {opaque = 0x7fffffffcc50 ""}
        word = (rspamd_stat_token_t *) 0x4074c00000000000
        words = (GArray *) 0x40000014ac
        io = (struct fuzzy_cmd_io *) 0x809506370
#2  0x0000000000572977 in fuzzy_generate_commands (task=0x8086b6700, rule=0x8070ef7a0, c=0, flag=0, value=0, flags=0)
    at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-a444ae8/src/plugins/fuzzy_check.c:2662
        fac = 1496
        short_text = 0
        part = (struct rspamd_mime_text_part *) 0x8097b2090
        mime_part = (struct rspamd_mime_part *) 0x9131cbe022a708ec
        image = (struct rspamd_image *) 0xc04cf
        io = (struct fuzzy_cmd_io *) 0x809506370
        cur = (struct fuzzy_cmd_io *) 0x7fffffffce10
        i = 1
        j = 0
        min_bytes = 1000
        res = (GPtrArray *) 0x80951fea0
#3  0x0000000000570d62 in fuzzy_symbol_callback (task=0x8086b6700, unused=0x0) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-a444ae8/src/plugins/fuzzy_check.c:2894
        rule = (struct fuzzy_rule *) 0x8070ef7a0
        i = 0
        commands = (GPtrArray *) 0x21ce4482
#4  0x000000000051c793 in rspamd_symbols_cache_check_symbol (task=0x8086b6700, cache=0x805440000, item=0x80687e550, checkpoint=0x80957bee0, total_diff=0x0)
    at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-a444ae8/src/libserver/symbols_cache.c:1350
        pending_before = 1
        pending_after = 1
        t1 = 787663.56716608198
        t2 = 0
        diff = 6.5189087763428688e-06
        ptask = (struct rspamd_task **) 0x0
        L = (lua_State *) 0x411d7c9885b2a1f6
        check = 1
        slow_diff_limit = 0.10000000000000001
#5  0x000000000051f8c6 in rspamd_symbols_cache_watcher_cb (sessiond=0x8086b6700, ud=0x805515200) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-a444ae8/src/libserver/symbols_cache.c:1284
        task = (struct rspamd_task *) 0x8086b6700
        item = (struct cache_item *) 0x805515200
        it = (struct cache_item *) 0x80687e550
        checkpoint = (struct cache_savepoint *) 0x80957bee0
        cache = (struct symbols_cache *) 0x805440000
        i = 2
        remain = 0
#6  0x00000000004f7c5f in rspamd_session_call_watcher_stack (session=0x80957c880, w=0x8095f14a0) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-a444ae8/src/libserver/events.c:183
        st = (struct rspamd_watch_stack *) 0x8095433d0
#7  0x00000000004f7b1b in rspamd_session_remove_event (session=0x80957c880, fin=0x4f3bd0 <rspamd_dns_fin_cb>, ud=0x8095059e0)
    at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-a444ae8/src/libserver/events.c:220
        search_ev = {subsystem = 72054193, fin = 0x4f3bd0 <rspamd_dns_fin_cb>, user_data = 0x8095059e0, w = 0x7fffffffd1b0}
        found_ev = (struct rspamd_async_event *) 0x809505a10
#8  0x00000000004f3ba1 in rspamd_dns_callback (reply=0x808bfb520, ud=0x8095059e0) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-a444ae8/src/libserver/dns.c:79
        reqdata = (struct rspamd_dns_request_ud *) 0x8095059e0
#9  0x0000000000622614 in rdns_process_read (fd=46, arg=0x806621380) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-a444ae8/contrib/librdns/resolver.c:281
        ioc = (struct rdns_io_channel *) 0x806621380
---Type <return> to continue, or q <return> to quit---
        resolver = (struct rdns_resolver *) 0x807a61c00
        req = (struct rdns_request *) 0x8086f9cc0
        r = 133
        rep = (struct rdns_reply *) 0x808bfb520
        in = 0x7fffffffd250 "\t▒\201\203"
#10 0x00000000004f57e2 in rdns_libevent_read_event (fd=46, what=2, ud=0x806621380) at rdns_event.h:82
No locals.
#11 0x0000000801e4106f in event_base_assert_ok_nolock_ () from /usr/local/lib/libevent-2.1.so.6
No symbol table info available.
#12 0x0000000801e3cf4e in event_base_loop () from /usr/local/lib/libevent-2.1.so.6
No symbol table info available.
#13 0x000000000042a6db in start_rspamd_proxy (worker=0x80876d900) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-a444ae8/src/rspamd_proxy.c:2206
        ctx = (struct rspamd_proxy_ctx *) 0x805606070
        rot_tv = {tv_sec = 79, tv_usec = 0}
#14 0x000000000052d172 in rspamd_fork_worker (rspamd_main=0x805433000, cf=0x8054d9c80, index=0, ev_base=0x808702100)
    at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-a444ae8/src/libserver/worker_util.c:678
        wrk = (struct rspamd_worker *) 0x80876d900
        rc = 0
        rlim = {rlim_cur = 104857600, rlim_max = 104857600}
#15 0x00000000004276fd in rspamd_fork_delayed_cb (signo=-1, what=1, arg=0x80877c1e0) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-a444ae8/src/rspamd.c:328
        w = (struct waiting_worker *) 0x80877c1e0
#16 0x0000000801e40da0 in event_base_assert_ok_nolock_ () from /usr/local/lib/libevent-2.1.so.6
No symbol table info available.
#17 0x0000000801e3cf4e in event_base_loop () from /usr/local/lib/libevent-2.1.so.6
No symbol table info available.
#18 0x0000000000424eaf in main (argc=1, argv=0x7fffffffeba0, env=0x7fffffffebe0) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-a444ae8/src/rspamd.c:1471
        i = 1
        res = 0
        signals = {__sigaction_u = {__sa_handler = 0, __sa_sigaction = 0}, sa_flags = 0, sa_mask = {__bits = 0x7fffffffeb04}}
        sigpipe_act = {__sigaction_u = {__sa_handler = 0x1, __sa_sigaction = 0x1}, sa_flags = 0, sa_mask = {__bits = 0x7fffffffeae4}}
        pworker = (worker_t **) 0x953158
        type = 1
        control_addr = (rspamd_inet_addr_t *) 0x8097e6210
        ev_base = (struct event_base *) 0x808702100
        term_ev = {ev_evcallback = {evcb_active_next = {tqe_next = 0x8009329f3, tqe_prev = 0x0}, evcb_flags = 128, evcb_pri = 0 '\0', evcb_closure = 1 '\001', evcb_cb_union = {
      evcb_callback = 0x425950 <rspamd_term_handler>, evcb_selfcb = 0x425950 <rspamd_term_handler>, evcb_evfinalize = 0x425950 <rspamd_term_handler>, evcb_cbfinalize = 0x425950 <rspamd_term_handler>},
    evcb_arg = 0x805433000}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0x7fffffffffff, tqe_prev = 0x7fffffffeae0}, min_heap_idx = -1}, ev_fd = 15, ev_base = 0x808702100, ev_ = {ev_io = {
      ev_io_next = {le_next = 0x0, le_prev = 0x8086b9160}, ev_timeout = {tv_sec = 140737488289792, tv_usec = 0}}, ev_signal = {ev_signal_next = {le_next = 0x0, le_prev = 0x8086b9160}, ev_ncalls = 0,
      ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_timeout = {tv_sec = 0, tv_usec = 34369540096}}
        int_ev = {ev_evcallback = {evcb_active_next = {tqe_next = 0x804411808, tqe_prev = 0x805416000}, evcb_flags = 128, evcb_pri = 0 '\0', evcb_closure = 1 '\001', evcb_cb_union = {
      evcb_callback = 0x425950 <rspamd_term_handler>, evcb_selfcb = 0x425950 <rspamd_term_handler>, evcb_evfinalize = 0x425950 <rspamd_term_handler>, evcb_cbfinalize = 0x425950 <rspamd_term_handler>},
    evcb_arg = 0x805433000}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0x7fffffffffff, tqe_prev = 0x803b2a7cc}, min_heap_idx = -1}, ev_fd = 2, ev_base = 0x808702100, ev_ = {ev_io = {
      ev_io_next = {le_next = 0x0, le_prev = 0x8086b9188}, ev_timeout = {tv_sec = 34432286720, tv_usec = 0}}, ev_signal = {ev_signal_next = {le_next = 0x0, le_prev = 0x8086b9188}, ev_ncalls = 0,
      ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_timeout = {tv_sec = 34369540096, tv_usec = 140737488349920}}
        cld_ev = {ev_evcallback = {evcb_active_next = {tqe_next = 0x0, tqe_prev = 0x8095e0030}, evcb_flags = 128, evcb_pri = 0 '\0', evcb_closure = 1 '\001', evcb_cb_union = {
      evcb_callback = 0x425ab0 <rspamd_cld_handler>, evcb_selfcb = 0x425ab0 <rspamd_cld_handler>, evcb_evfinalize = 0x425ab0 <rspamd_cld_handler>, evcb_cbfinalize = 0x425ab0 <rspamd_cld_handler>},
    evcb_arg = 0x805433000}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0xffffffff, tqe_prev = 0x80095b030}, min_heap_idx = -1}, ev_fd = 20, ev_base = 0x808702100, ev_ = {ev_io = {
      ev_io_next = {le_next = 0x0, le_prev = 0x8086b9198}, ev_timeout = {tv_sec = 109707264, tv_usec = 0}}, ev_signal = {ev_signal_next = {le_next = 0x0, le_prev = 0x8086b9198}, ev_ncalls = 0,
      ev_pncalls = 0x0}}, ev_events = 24, ev_res = 8, ev_timeout = {tv_sec = 1, tv_usec = 34369540096}}
        hup_ev = {ev_evcallback = {evcb_active_next = {tqe_next = 0x0, tqe_prev = 0x0}, evcb_flags = 128, evcb_pri = 0 '\0', evcb_closure = 1 '\001', evcb_cb_union = {
      evcb_callback = 0x4259f0 <rspamd_hup_handler>, evcb_selfcb = 0x4259f0 <rspamd_hup_handler>, evcb_evfinalize = 0x4259f0 <rspamd_hup_handler>, evcb_cbfinalize = 0x4259f0 <rspamd_hup_handler>},
    evcb_arg = 0x805433000}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0xffffffff, tqe_prev = 0x68acf04}, min_heap_idx = -1}, ev_fd = 1, ev_base = 0x808702100, ev_ = {ev_io = {
      ev_io_next = {le_next = 0x0, le_prev = 0x8086b9190}, ev_timeout = {tv_sec = 0, tv_usec = 0}}, ev_signal = {ev_signal_next = {le_next = 0x0, le_prev = 0x8086b9190}, ev_ncalls = 0, ev_pncalls = 0x0}},
  ev_events = 24, ev_res = 0, ev_timeout = {tv_sec = 0, tv_usec = 140737488349136}}
        usr1_ev = {ev_evcallback = {evcb_active_next = {tqe_next = 0x800957400, tqe_prev = 0x800957800}, evcb_flags = 128, evcb_pri = 0 '\0', evcb_closure = 1 '\001', evcb_cb_union = {
      evcb_callback = 0x426030 <rspamd_usr1_handler>, evcb_selfcb = 0x426030 <rspamd_usr1_handler>, evcb_evfinalize = 0x426030 <rspamd_usr1_handler>, evcb_cbfinalize = 0x426030 <rspamd_usr1_handler>},
    evcb_arg = 0x805433000}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0x8ffffffff, tqe_prev = 0x800958c00}, min_heap_idx = -1}, ev_fd = 30, ev_base = 0x808702100, ev_ = {ev_io = {
      ev_io_next = {le_next = 0x0, le_prev = 0x8086b91a0}, ev_timeout = {tv_sec = 0, tv_usec = 0}}, ev_signal = {ev_signal_next = {le_next = 0x0, le_prev = 0x8086b91a0}, ev_ncalls = 0, ev_pncalls = 0x0}},
  ev_events = 24, ev_res = 0, ev_timeout = {tv_sec = 0, tv_usec = 0}}
        control_ev = {ev_evcallback = {evcb_active_next = {tqe_next = 0x0, tqe_prev = 0x8095e0030}, evcb_flags = 128, evcb_pri = 0 '\0', evcb_closure = 2 '\002', evcb_cb_union = {
      evcb_callback = 0x426a30 <rspamd_control_handler>, evcb_selfcb = 0x426a30 <rspamd_control_handler>, evcb_evfinalize = 0x426a30 <rspamd_control_handler>,
---Type <return> to continue, or q <return> to quit---
      evcb_cbfinalize = 0x426a30 <rspamd_control_handler>}, evcb_arg = 0x805433000}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0x8ffffffff, tqe_prev = 0x800950c00}, min_heap_idx = -1},
  ev_fd = 5, ev_base = 0x808702100, ev_ = {ev_io = {ev_io_next = {le_next = 0x0, le_prev = 0x807bff580}, ev_timeout = {tv_sec = 0, tv_usec = 0}}, ev_signal = {ev_signal_next = {le_next = 0x0,
        le_prev = 0x807bff580}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 18, ev_res = 2, ev_timeout = {tv_sec = 34369522688, tv_usec = 34369531904}}
        term_tv = {tv_sec = 217, tv_usec = 34369503232}
        rspamd_main = (struct rspamd_main *) 0x805433000
        skip_pid = 0
        valgrind_mode = 0
(gdb) q
```

**Comment by moisseev** [comment]
Fixed.
