### ISSUE TITLE
bayes learn

### ISSUE THREAD

**Issue by Dmitry55** [vstakhov/rspamd#588]
After last update learning bays not working
Summary:
  Rspamd client version 1.2.3
  Release id: d5bd632

rspamc -c bayes learn_spam /test/spam.eml
Results for file: /test/spam.eml (0.187 seconds)
IO read error: unexpected EOF

**Comment by piwats** [comment]
I got that same error for ```rspamc``` stat, which disappeared after a restart of rspamd. Since then I have not seen it again.

**Comment by Dmitry55** [comment]
Reboot does not help. The problem arises when statistics are stored in radis, there are no problems with sqlite3.

**Comment by vstakhov** [comment]
I don't see any rspamd logs here.

**Comment by Dmitry55** [comment]
2016-04-14 16:21:05 #10175(controller) <a5eff8>; task; convert_text_to_utf: <20160331125003.4PSOZTEZZW5SA@www.inbox.ru>: cannot convert from koi8-r to utf8: output of size 2359 is not enough to handle converison of 168 bytes
2016-04-14 16:21:05 #10175(controller) <a5eff8>; task; rspamd_message_parse: loaded message; id: <20160331125003.4PSOZTEZZW5SA@www.inbox.ru>; queue-id: <undef>
2016-04-14 16:21:05 #10146(main) <594cca>; main; rspamd_cld_handler: controller process 10175 terminated abnormally by signal: 11 and created core file

**Comment by fatalbanana** [comment]
Looks like controller is crashing:
```
Program received signal SIGSEGV, Segmentation fault.
redisAsyncFree (ac=0x0) at /home/dru/r/rspamd-1.2.3/contrib/hiredis/async.c:325
325	    c->flags |= REDIS_FREEING;
(gdb) bt full
#0  redisAsyncFree (ac=0x0) at /home/dru/r/rspamd-1.2.3/contrib/hiredis/async.c:325
        c = 0x0
#1  0x00000000004a04d8 in rspamd_redis_learned (c=<optimized out>, r=<optimized out>, priv=0x7f19ed505140)
    at /home/dru/r/rspamd-1.2.3/src/libstat/backends/redis_backend.c:889
        rt = 0x7f19ed505140
        task = 0x7f19ed4d8110
        __func__ = "rspamd_redis_learned"
#2  0x00000000004df283 in __redisRunCallback (cb=0x7ffc19529f30, cb=0x7ffc19529f30, reply=<optimized out>, ac=0x7f19ee93b100)
    at /home/dru/r/rspamd-1.2.3/contrib/hiredis/async.c:269
        c = 0x7f19ee93b100
#3  redisProcessCallbacks (ac=0x7f19ee93b100) at /home/dru/r/rspamd-1.2.3/contrib/hiredis/async.c:469
        c = 0x7f19ee93b100
        cb = {next = 0x0, fn = 0x4a0450 <rspamd_redis_learned>, privdata = 0x7f19ed505140}
        reply = 0x7f19ed492340
        status = <optimized out>
        __PRETTY_FUNCTION__ = "redisProcessCallbacks"
#4  0x00007f19f1d33f24 in event_process_active_single_queue (activeq=0x7f19eeb42ef0, base=0x7f19ee810c00) at event.c:1350
        ev = 0x7f19ee896688
        count = 1
#5  event_process_active (base=<optimized out>) at event.c:1420
        activeq = 0x7f19eeb42ef0
        i = 0
        c = 0
#6  event_base_loop (base=0x7f19ee810c00, flags=flags@entry=0) at event.c:1621
        evsel = 0x7f19f1f688e0 <epollops>
        tv = {tv_sec = 0, tv_usec = 499533}
        tv_p = <optimized out>
        res = <optimized out>
        done = 0
        retval = 0
        __func__ = "event_base_loop"
#7  0x0000000000426dc4 in start_controller_worker (worker=0x7f19ed4a0800) at /home/dru/r/rspamd-1.2.3/src/controller.c:2686
        ctx = 0x7f19ee86c720
        cur = <optimized out>
        mctx = <optimized out>
        iter = {dummy1 = 0x7f19ee9f0520, dummy2 = 0x0, dummy3 = 0x173, dummy4 = 8, dummy5 = 0, dummy6 = 0xbb00000002}
---Type <return> to continue, or q <return> to quit---
        key = 0x52a648
        value = 0x7f19eea89440
        cache = <optimized out>
        secure_ip = <optimized out>
        m = <optimized out>
        __func__ = "start_controller_worker"
#8  0x0000000000498566 in rspamd_fork_worker (rspamd_main=rspamd_main@entry=0x7f19ee866080, cf=cf@entry=0x7f19ee967540, index=index@entry=0, 
    ev_base=ev_base@entry=0x7f19ee810c00) at /home/dru/r/rspamd-1.2.3/src/libserver/worker_util.c:563
        wrk = 0x7f19ed4a0800
        rc = <optimized out>
        rlim = {rlim_cur = 104857600, rlim_max = 104857600}
        __func__ = "rspamd_fork_worker"
#9  0x000000000042b503 in spawn_worker_type (rspamd_main=0x7f19ee866080, ev_base=0x7f19ee810c00, cf=0x7f19ee967540) at /home/dru/r/rspamd-1.2.3/src/rspamd.c:448
        i = 0
#10 0x000000000042b746 in spawn_workers (rspamd_main=rspamd_main@entry=0x7f19ee866080, ev_base=ev_base@entry=0x7f19ee810c00)
    at /home/dru/r/rspamd-1.2.3/src/rspamd.c:529
        cur = <optimized out>
        ls = <optimized out>
        cf = <optimized out>
        p = <optimized out>
        bcf = <optimized out>
        listen_ok = <optimized out>
        seen_mandatory_workers = 0x7f19eead6b40
        cw = <optimized out>
        wrk = <optimized out>
        i = <optimized out>
        __func__ = "spawn_workers"
#11 0x0000000000422913 in main (argc=1, argv=0x7ffc1952a8e8, env=<optimized out>) at /home/dru/r/rspamd-1.2.3/src/rspamd.c:1237
        i = <optimized out>
        res = 0
        signals = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = 0, sa_restorer = 0x0}
        sigpipe_act = {__sigaction_handler = {sa_handler = 0x1, sa_sigaction = 0x1}, sa_mask = {__val = {4096, 0 <repeats 15 times>}}, sa_flags = 0, 
          sa_restorer = 0x1}
        pworker = <optimized out>
        type = <optimized out>
        control_addr = 0x7f19eead6010
---Type <return> to continue, or q <return> to quit---
        ev_base = 0x7f19ee810c00
        term_ev = {ev_active_next = {tqe_next = 0x7ffc195f3160, tqe_prev = 0x7ffc1952a470}, ev_next = {tqe_next = 0x7ffc1952a3c0, tqe_prev = 0x7f19ee810d60}, 
          ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0x7f19ffffffff, tqe_prev = 0xd827590}, min_heap_idx = -1}, ev_fd = 15, 
          ev_base = 0x7f19ee810c00, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x7f19eeb42f30}, ev_timeout = {tv_sec = 0, tv_usec = 0}}, ev_signal = {
              ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x7f19eeb42f30}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, 
          ev_pri = 0 '\000', ev_closure = 1 '\001', ev_timeout = {tv_sec = 140720733332688, tv_usec = 139749401241200}, ev_callback = 0x42ae50 <rspamd_term_handler>, 
          ev_arg = 0x7f19ee866080}
        int_ev = {ev_active_next = {tqe_next = 0x0, tqe_prev = 0x7f19f2fb3dc9 <check_match+89>}, ev_next = {tqe_next = 0x7ffc1952a4e0, tqe_prev = 0x7f19ee810d60}, 
          ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0xffffffff, tqe_prev = 0x7f19eec000c0}, min_heap_idx = -1}, ev_fd = 2, 
          ev_base = 0x7f19ee810c00, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x7f19eeb42f60}, ev_timeout = {tv_sec = 139749422137344, tv_usec = 0}}, 
            ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x7f19eeb42f60}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, 
          ev_pri = 0 '\000', ev_closure = 1 '\001', ev_timeout = {tv_sec = 7, tv_usec = 139749352275968}, ev_callback = 0x42ae50 <rspamd_term_handler>, 
          ev_arg = 0x7f19ee866080}
        cld_ev = {ev_active_next = {tqe_next = 0x7f19f31cba40, tqe_prev = 0x7f19eec000c0}, ev_next = {tqe_next = 0x7ffc1952a570, tqe_prev = 0x7f19ee810d60}, 
          ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0xffffffff, tqe_prev = 0xb10965d4}, min_heap_idx = -1}, ev_fd = 17, ev_base = 0x7f19ee810c00, 
          _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x7f19eeb42f10}, ev_timeout = {tv_sec = 0, tv_usec = 0}}, ev_signal = {ev_signal_next = {
                tqe_next = 0x0, tqe_prev = 0x7f19eeb42f10}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, ev_pri = 0 '\000', 
          ev_closure = 1 '\001', ev_timeout = {tv_sec = 139749427461788, tv_usec = 139749401245016}, ev_callback = 0x42b120 <rspamd_cld_handler>, 
          ev_arg = 0x7f19ee866080}
        hup_ev = {ev_active_next = {tqe_next = 0x398, tqe_prev = 0x7f19eec000c0}, ev_next = {tqe_next = 0x7ffc1952a450, tqe_prev = 0x7f19ee810d60}, ev_timeout_pos = {
            ev_next_with_common_timeout = {tqe_next = 0x7f19ffffffff, tqe_prev = 0x68}, min_heap_idx = -1}, ev_fd = 1, ev_base = 0x7f19ee810c00, _ev = {ev_io = {
              ev_io_next = {tqe_next = 0x0, tqe_prev = 0x7f19eeb42ed0}, ev_timeout = {tv_sec = 0, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, 
                tqe_prev = 0x7f19eeb42ed0}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, ev_pri = 0 '\000', ev_closure = 1 '\001', 
          ev_timeout = {tv_sec = 139749415406630, tv_usec = 139749401267576}, ev_callback = 0x42bdf0 <rspamd_hup_handler>, ev_arg = 0x7f19ee866080}
        usr1_ev = {ev_active_next = {tqe_next = 0x1000, tqe_prev = 0x7f19f2fb3e9c <check_match+300>}, ev_next = {tqe_next = 0x7f19ed4a0958, 
            tqe_prev = 0x7f19ee810d60}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0xffffffff, tqe_prev = 0x1b}, min_heap_idx = -1}, ev_fd = 10, 
          ev_base = 0x7f19ee810c00, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x7f19eeb42f20}, ev_timeout = {tv_sec = 139749401165824, tv_usec = 0}}, 
            ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x7f19eeb42f20}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, 
          ev_pri = 0 '\000', ev_closure = 1 '\001', ev_timeout = {tv_sec = 66985346, tv_usec = 140720733333232}, ev_callback = 0x42ade0 <rspamd_usr1_handler>, 
          ev_arg = 0x7f19ee866080}
        control_ev = {ev_active_next = {tqe_next = 0x7f19f31b74f0, tqe_prev = 0x7f19f12e877f}, ev_next = {tqe_next = 0x7f19f16b8d78, 
            tqe_prev = 0x7f19f2fb3e9c <check_match+300>}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0x100000000, tqe_prev = 0xf63d4e2e}, 
            min_heap_idx = 0}, ev_fd = 10, ev_base = 0x1b, _ev = {ev_io = {ev_io_next = {tqe_next = 0x7f19f31b1210, tqe_prev = 0x7f19f2fb4816 <do_lookup_x+2342>}, 
              ev_timeout = {tv_sec = 1, tv_usec = 140720733333136}}, ev_signal = {ev_signal_next = {tqe_next = 0x7f19f31b1210, 
                tqe_prev = 0x7f19f2fb4816 <do_lookup_x+2342>}, ev_ncalls = 1, ev_pncalls = 0x7ffc1952a690}}, ev_events = -17112, ev_res = -3734, ev_flags = 32537, 
          ev_pri = 0 '\000', ev_closure = 0 '\000', ev_timeout = {tv_sec = 140720733333408, tv_usec = 139749401264552}, ev_callback = 0x3d8f538, 
---Type <return> to continue, or q <return> to quit---
          ev_arg = 0x7ffc1952a790}
        term_tv = {tv_sec = 139749401235104, tv_usec = 140720733332320}
        __func__ = "main"
(gdb) 
```

**Comment by setiseta** [comment]
Same over webui learn
