### ISSUE TITLE
Segmentation fault rspamd normal process

### ISSUE THREAD

**Issue by AlexeySa** [vstakhov/rspamd#654]
Rspamd 1.2.7 (build May 27)
```
gdb /usr/local/rspamd/bin/rspamd-1.2.7 /tmp/core-rspamd-11-489-489-948102-1465423389
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-90.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/rspamd/bin/rspamd-1.2.7...done.

warning: core file may not match specified executable file.
[New Thread 948102]
.......
....
Core was generated by `rspamd: normal process                                                        '.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f506e032321 in __strlen_sse2 () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install file-libs-5.04-30.el6.x86_64 glibc-2.12-1.192.el6.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-57.el6.x86_64 libcom_err-1.41.12-22.el6.x86_64 libffi-3.0.5-3.2.el6.x86_64 libgcc-4.4.7-17.el6.x86_64 libselinux-2.0.94-7.el6.x86_64 openssl-1.0.1e-48.el6_8.1.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt
#0  0x00007f506e032321 in __strlen_sse2 () from /lib64/libc.so.6
#1  0x00007f506ce3bc52 in ?? () from /usr/local/rspamd/lib/rspamd/libluajit-5.1.so.2
#2  0x0000000000474ffb in lua_tcp_push_error (cbd=0x1659bc0, err=0x51e3ac "unable to resolve host: %s") at /root/src/rspamd/rspamd-1.2.7/src/lua/lua_tcp.c:132
#3  0x0000000000475593 in lua_tcp_dns_handler (reply=0x16c9e70, ud=0x1659bc0) at /root/src/rspamd/rspamd-1.2.7/src/lua/lua_tcp.c:370
#4  0x0000000000485d1b in rspamd_dns_callback (reply=0x16c9e70, ud=<value optimized out>) at /root/src/rspamd/rspamd-1.2.7/src/libserver/dns.c:66
#5  0x00000000005037f0 in rdns_process_read (fd=<value optimized out>, arg=<value optimized out>) at /root/src/rspamd/rspamd-1.2.7/contrib/librdns/resolver.c:282
#6  0x00007f506e6211d5 in event_persist_closure (base=0x1702f70, flags=0) at event.c:1319
#7  event_process_active_single_queue (base=0x1702f70, flags=0) at event.c:1363
#8  event_process_active (base=0x1702f70, flags=0) at event.c:1438
#9  event_base_loop (base=0x1702f70, flags=0) at event.c:1639
#10 0x000000000042df22 in start_worker (worker=0x1702e10) at /root/src/rspamd/rspamd-1.2.7/src/worker.c:527
#11 0x00000000004989bf in rspamd_fork_worker (rspamd_main=0x13a4f50, cf=0x1701950, index=<value optimized out>, ev_base=0x16e1dd0)
    at /root/src/rspamd/rspamd-1.2.7/src/libserver/worker_util.c:563
#12 0x000000000042c276 in rspamd_fork_delayed_cb (signo=<value optimized out>, what=<value optimized out>, arg=<value optimized out>)
    at /root/src/rspamd/rspamd-1.2.7/src/rspamd.c:318
#13 0x00007f506e620f0c in event_process_active_single_queue (base=0x16e1dd0, flags=0) at event.c:1368
#14 event_process_active (base=0x16e1dd0, flags=0) at event.c:1438
#15 event_base_loop (base=0x16e1dd0, flags=0) at event.c:1639
#16 0x000000000042b7ee in main (argc=1, argv=0x7ffc2cf166f8, env=<value optimized out>) at /root/src/rspamd/rspamd-1.2.7/src/rspamd.c:1271
```

**Comment by AlexeySa** [comment]
Thank you!
