### ISSUE TITLE
Controller crash when learning spam on OpenBSD

### ISSUE THREAD

**Issue by vext01** [vstakhov/rspamd#961]
Learning spam from the 2016-08 corpus here:
http://untroubled.org/spam/

I used:

```
rspamc learn_spam .
```

Eventually controllers will start crashing causing IO errors on rspamc:
```
Results for file: ./1470093978.23671_9.lorien (2.640 seconds)
IO read error: unexpected EOF
```

The EOF is caused when the controller socket disappears due to a crash, and then rspamc tries to read it.

Here is a trace on a crashing controller:

```
$ egdb rspamd -c rspamd.core
GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-openbsd6.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from rspamd...done.
[New process 47877]
Core was generated by `rspamd'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00001683a2561efa in thrkill () at <stdin>:2
2       <stdin>: No such file or directory.
(gdb) bt
#0  0x00001683a2561efa in thrkill () at <stdin>:2
#1  0x00001683a253bd19 in *_libc_abort () at /usr/src/lib/libc/stdlib/abort.c:52
#2  0x00001683a259dda8 in *_libc_memcpy (dst0=<optimized out>, src0=<optimized out>, length=<optimized out>) at /usr/src/lib/libc/string/memcpy.c:65
#3  0x000016815adb74fc in rspamd_html_decode_entitles_inplace (
    s=0x16841ee6b9d1 "&darr\344\270\213\350\250\230\343\202\210\343\202\212\343\201\224\345\215\224\345\212\233\343\202\222\343\201\212\351\241\230\343\201\204\350\207\264\343\201\227\343\201\276\343\201\231\231&darr", len=<optimized out>) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libserver/html.c:739
#4  0x000016815adb93c0 in rspamd_html_process_part_full (pool=0x168402d13460, hc=0x1683cb213c80, in=<optimized out>, exceptions=0x1683cb213c28, urls=0x16840042ac60, emails=0x1683b1090400)
    at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libserver/html.c:1926
#5  0x000016815add940e in process_text_part (is_empty=<optimized out>, parent=0x1683ad3bc240, mime_part=<optimized out>, type=<optimized out>, part_content=0x1683cb213c70, task=<optimized out>)
    at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libmime/message.c:958
#6  mime_foreach_callback (parent=<optimized out>, part=<optimized out>, user_data=0x7f7ffffe9e30) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libmime/message.c:1236
#7  0x00001683fed9b0a7 in multipart_foreach () from /usr/local/lib/libgmime-2.6.so.0.1
#8  0x000016815add7d90 in rspamd_message_parse (task=0x1683c55242b0) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libmime/message.c:1512
#9  0x000016815adc4635 in rspamd_task_process (task=0x1683c55242b0, stages=15591) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libserver/task.c:579
#10 0x000016815adc4682 in rspamd_task_process (task=0x1683c55242b0, stages=15591) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libserver/task.c:688
#11 0x000016815adc4682 in rspamd_task_process (task=0x1683c55242b0, stages=15591) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libserver/task.c:688
#12 0x000016815ad3c573 in rspamd_controller_handle_learn_common (conn_ent=0x168433662660, msg=0x1683fe88f1f0, is_spam=1) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/controller.c:1542
#13 0x000016815ad6f83e in rspamd_http_router_finish_handler (conn=<optimized out>, msg=0x1683fe88f1f0) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libutil/http.c:2940
#14 0x000016815ad6d4cb in rspamd_http_on_message_complete (parser=<optimized out>) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libutil/http.c:908
#15 0x000016815ae41403 in http_parser_execute (parser=0x1683f38526c0, settings=0x1683f38526e0,
    data=0x1683b0b27010 "POST /learnspam HTTP/1.0\r\nContent-Length: 2720\r\nUser-Agent: rspamc\r\n\r\nDelivered-To: bruce@bruce-guenter.dyndns.org\nReceived: (qmail 32494 invoked from network); 31 Jul 2016 17:55:46 -0000\nReceived: fr"..., len=2790) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/contrib/http-parser/http_parser.c:1772
#16 0x000016815ad6d1ba in rspamd_http_event_handler (fd=<optimized out>, what=<optimized out>, ud=0x16840c25b5e0) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libutil/http.c:1121
#17 0x00001683f3ad9898 in event_process_active (base=<optimized out>) at /usr/src/lib/libevent/event.c:350
#18 event_base_loop (base=0x168419c11000, flags=<optimized out>) at /usr/src/lib/libevent/event.c:502
#19 0x000016815ad39e2b in start_controller_worker (worker=0x168444f0dd00) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/controller.c:2844
#20 0x000016815adc8c6f in rspamd_fork_worker (rspamd_main=0x16840b531a00, cf=0x1683b2ccb770, index=<optimized out>, ev_base=0x16840c25b400)
    at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libserver/worker_util.c:596
#21 0x000016815ad43053 in spawn_worker_type (rspamd_main=0x16840b531a00, ev_base=0x16840c25b400, cf=0x1683b2ccb770) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/rspamd.c:514
#22 0x000016815ad43458 in spawn_workers (rspamd_main=0x16840b531a00, ev_base=0x16840c25b400) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/rspamd.c:596
#23 0x000016815ad44dc2 in main (argc=1, argv=0x7f7ffffeab38, env=<optimized out>) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/rspamd.c:1335
```
This is 1.3.5 on OpenBSD-6.

Let me know if I can give any more info.

**Comment by vext01** [comment]
At cebka's request, I'm attaching one of the spam files which *sometimes* causes a crash.

Original filename was 1470093978.23671_9.lorien, renamed for github to allow upload.
[1470093978.23671_9.txt](https://github.com/vstakhov/rspamd/files/482285/1470093978.23671_9.txt)

**Comment by vext01** [comment]
Here's some more info:

```
(gdb) frame 3                                  
#3  0x000016815adb74fc in rspamd_html_decode_entitles_inplace (
    s=0x16841ee6b9d1 "&darr�\213�\230�\202\210�\202\212�\201\224�\215\224�\212\233�\202\222�\201\212�\230�\201\204�\207��\201\227�\201��\201\231\231&darr", len=Variable "len" is not available.
)
    at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libserver/html.c:739
739                                                                     memcpy (t, e, h - e);
Current language:  auto; currently c
(gdb) p t
$1 = (gchar *) 0x16841ee6ba08 "r"
(gdb) p e
$2 = (gchar *) 0x16841ee6ba04 "&darr"
(gdb) p h
$3 = (gchar *) 0x16841ee6ba09 ""
```

**Comment by vext01** [comment]
Note that the trace may not triggered from the same spam file as I uploaded. There were lots failing.

**Comment by vext01** [comment]
I've applied this locally. Looks like it has fixed the crash. Let's close this unless it shows up again.
