### ISSUE TITLE
Crash in url_email_start() on OpenBSD

### ISSUE THREAD

**Issue by vext01** [vstakhov/rspamd#969]
Learning spam from the 2016-08 corpus here:
http://untroubled.org/spam/

```
Core was generated by `rspamd'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  url_email_start (cb=0x7f7ffffbd850,
    pos=0x16c896609000 "@import url(http://fine.br-hfz.win/Jisggqtfs/hbgcqt1189hbmhcx/uVtkgkI4HseKuRVhPrwmRvqQS9VtSK93hFnTL8onFLU/9u6gK5bh6KU7UOZQedhlQySzvpdrof4lIlZPoJK2d-Y4-96sxhFRjfVORq6OFueA1nKGXGI78x3ThYXM2lJZYF1suelrDk"..., match=0x7f7ffffbd400) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libserver/url.c:1931
1931                    match->st = *(pos - 1);
(gdb) bt
#0  url_email_start (cb=0x7f7ffffbd850,
    pos=0x16c896609000 "@import url(http://fine.br-hfz.win/Jisggqtfs/hbgcqt1189hbmhcx/uVtkgkI4HseKuRVhPrwmRvqQS9VtSK93hFnTL8onFLU/9u6gK5bh6KU7UOZQedhlQySzvpdrof4lIlZPoJK2d-Y4-96sxhFRjfVORq6OFueA1nKGXGI78x3ThYXM2lJZYF1suelrDk"..., match=0x7f7ffffbd400) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libserver/url.c:1931
#1  0x000016c59fec82aa in rspamd_url_trie_generic_callback_common (mp=<optimized out>, strnum=<optimized out>, match_start=0, match_pos=1,
    text=0x16c896609000 "@import url(http://fine.br-hfz.win/Jisggqtfs/hbgcqt1189hbmhcx/uVtkgkI4HseKuRVhPrwmRvqQS9VtSK93hFnTL8onFLU/9u6gK5bh6KU7UOZQedhlQySzvpdrof4lIlZPoJK2d-Y4-96sxhFRjfVORq6OFueA1nKGXGI78x3ThYXM2lJZYF1suelrDk"..., len=<optimized out>, context=0x7f7ffffbd850, multiple=1) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libserver/url.c:2227
#2  0x000016c59fec857a in rspamd_url_trie_generic_callback_multiple (mp=0x7f7ffffbd850, strnum=2522910720, match_start=-273408, match_pos=-1772048329, text=0x16c7fd1d4460 "", len=10831, context=0x7f7ffffbd850)
    at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libserver/url.c:2278
#3  0x000016c59fef58ec in rspamd_multipattern_acism_cb (strnum=15, textpos=-1772048329, context=0x7f7ffffbd7e0) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libutil/multipattern.c:625
#4  0x000016c8628e675d in acism_lookup (psp=<optimized out>, text=<optimized out>, len=<optimized out>, cb=0x16c59fef58b0 <rspamd_multipattern_acism_cb>, context=0x7f7ffffbd7e0, statep=0x7f7ffffbd814,
    caseless=true) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/contrib/aho-corasick/acism.c:89
#5  0x000016c59fef5ac6 in rspamd_multipattern_lookup (mp=<optimized out>,
    in=0x16c896609000 "@import url(http://fine.br-hfz.win/Jisggqtfs/hbgcqt1189hbmhcx/uVtkgkI4HseKuRVhPrwmRvqQS9VtSK93hFnTL8onFLU/9u6gK5bh6KU7UOZQedhlQySzvpdrof4lIlZPoJK2d-Y4-96sxhFRjfVORq6OFueA1nKGXGI78x3ThYXM2lJZYF1suelrDk"..., len=140187732268032, cb=<optimized out>, ud=<optimized out>, pnfound=0x0) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libutil/multipattern.c:693
#6  0x000016c59fec6f24 in rspamd_url_find_multiple (pool=0x16c897116980,
    in=0x16c896609000 "@import url(http://fine.br-hfz.win/Jisggqtfs/hbgcqt1189hbmhcx/uVtkgkI4HseKuRVhPrwmRvqQS9VtSK93hFnTL8onFLU/9u6gK5bh6KU7UOZQedhlQySzvpdrof4lIlZPoJK2d-Y4-96sxhFRjfVORq6OFueA1nKGXGI78x3ThYXM2lJZYF1suelrDk"..., inlen=10831, is_html=0, nlines=0x16c7fd1d4460, func=0x16c59fec7f70 <rspamd_url_text_part_callback>, ud=0x7f7ffffbd910) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libserver/url.c:2418
#7  0x000016c59fec7488 in rspamd_url_text_extract (pool=<optimized out>, task=0x16c805d20bd0, part=0x16c7ebcab4f0, is_html=-1772048329) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libserver/url.c:2383
#8  0x000016c59fed98b9 in process_text_part (is_empty=<optimized out>, parent=0x16c87ec9a029, mime_part=<optimized out>, type=<optimized out>, part_content=<optimized out>, task=<optimized out>)
    at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libmime/message.c:1034
#9  mime_foreach_callback (parent=<optimized out>, part=<optimized out>, user_data=<optimized out>) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libmime/message.c:1236
#10 0x000016c7e373e0a7 in multipart_foreach () from /usr/local/lib/libgmime-2.6.so.0.1
#11 0x000016c59fed7d60 in rspamd_message_parse (task=0x16c805d20bd0) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libmime/message.c:1512
#12 0x000016c59fec4605 in rspamd_task_process (task=0x16c805d20bd0, stages=15591) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libserver/task.c:579
#13 0x000016c59fec4652 in rspamd_task_process (task=0x16c805d20bd0, stages=15591) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libserver/task.c:688
#14 0x000016c59fec4652 in rspamd_task_process (task=0x16c805d20bd0, stages=15591) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libserver/task.c:688
#15 0x000016c59fe3c573 in rspamd_controller_handle_learn_common (conn_ent=0x16c887c8d0d0, msg=0x16c7b422b0d0, is_spam=1) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/controller.c:1542
#16 0x000016c59fe6f83e in rspamd_http_router_finish_handler (conn=<optimized out>, msg=0x16c7b422b0d0) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libutil/http.c:2940
#17 0x000016c59fe6d4cb in rspamd_http_on_message_complete (parser=<optimized out>) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libutil/http.c:908
#18 0x000016c59ff413d3 in http_parser_execute (parser=0x16c7fbec5030, settings=0x16c7fbec5050,
    data=0x16c88124cfc9 "\n\t\t\t\t\t\t</td>\n\n\n\t\t\t\t\t\t<td align=\"left\" bgcolor=\"#f7f7f7\" class=\"gutter  tablet-hide\" valign=\"top\">&nbsp;</td>\n\n\n\t\t\t\t\t</tr>\n\n\n\t\t\t\t\t<tr>\n\n\n\t\t\t\t\t\t<td align=\"right\" bgcolor=\"#2a2a2a\" class=\"gutter  tablet-"..., len=4860) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/contrib/http-parser/http_parser.c:1772
#19 0x000016c59fe6d1ba in rspamd_http_event_handler (fd=<optimized out>, what=<optimized out>, ud=0x16c7bf8af450) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libutil/http.c:1121
#20 0x000016c805781898 in event_process_active (base=<optimized out>) at /usr/src/lib/libevent/event.c:350
#21 event_base_loop (base=0x16c8214e8c00, flags=<optimized out>) at /usr/src/lib/libevent/event.c:502
#22 0x000016c59fe39e2b in start_controller_worker (worker=0x16c83a7ccb00) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/controller.c:2844
#23 0x000016c59fec8c3f in rspamd_fork_worker (rspamd_main=0x16c7b283b980, cf=0x16c894daa770, index=<optimized out>, ev_base=0x16c897116000)
    at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libserver/worker_util.c:596
#24 0x000016c59fe43053 in spawn_worker_type (rspamd_main=0x16c7b283b980, ev_base=0x16c897116000, cf=0x16c894daa770) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/rspamd.c:514
#25 0x000016c59fe43458 in spawn_workers (rspamd_main=0x16c7b283b980, ev_base=0x16c897116000) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/rspamd.c:596
#26 0x000016c59fe44dc2 in main (argc=1, argv=0x7f7ffffbe9b8, env=<optimized out>) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/rspamd.c:1335
(gdb) list
1926                            return FALSE;
1927                    }
1928            }
1929
1930            if (pos > cb->begin - 1) {
1931                    match->st = *(pos - 1);
1932            }
1933            else {
1934                    match->st = '\0';
1935            }
(gdb) p match
$1 = (url_match_t *) 0x7f7ffffbd400
(gdb) p match->st
$2 = 0 '\000'
(gdb) p pos
$3 = (const gchar *) 0x16c896609000 "@import url(http://fine.br-hfz.win/Jisggqtfs/hbgcqt1189hbmhcx/uVtkgkI4HseKuRVhPrwmRvqQS9VtSK93hFnTL8onFLU/9u6gK5bh6KU7UOZQedhlQySzvpdrof4lIlZPoJK2d-Y4-96sxhFRjfVORq6OFueA1nKGXGI78x3ThYXM2lJZYF1suelrDk"...
(gdb) p *(pos - 1)
Cannot access memory at address 0x16c896608fff
(gdb) p *(pos)
$4 = 64 '@'
```

Looks like a buffer underflow to me.

**Comment by vext01** [comment]
Here's another example:

```
(gdb) bt
#0  url_email_start (cb=0x7f7ffffbda70,
    pos=0x16c84cd59000 "@media all and (max-width:590px) {*.responsive {width: 290px !important;}*#center {width: 50%;margin: 0 auto;display: table;}*.responsive-spacer table {width: 20px !important;}ulian Zelizer is a profe"..., match=0x7f7ffffbd620) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libserver/url.c:1931
#1  0x000016c59fec82aa in rspamd_url_trie_generic_callback_common (mp=<optimized out>, strnum=<optimized out>, match_start=0, match_pos=1,
    text=0x16c84cd59000 "@media all and (max-width:590px) {*.responsive {width: 290px !important;}*#center {width: 50%;margin: 0 auto;display: table;}*.responsive-spacer table {width: 20px !important;}ulian Zelizer is a profe"..., len=<optimized out>, context=0x7f7ffffbda70, multiple=1) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libserver/url.c:2227
#2  0x000016c59fec857a in rspamd_url_trie_generic_callback_multiple (mp=0x7f7ffffbda70, strnum=1289064448, match_start=-272864, match_pos=1289069270, text=0x16c7f4b6eb20 "", len=9071, context=0x7f7ffffbda70)
    at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libserver/url.c:2278
#3  0x000016c59fef58ec in rspamd_multipattern_acism_cb (strnum=15, textpos=1289069270, context=0x7f7ffffbda00) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libutil/multipattern.c:625
#4  0x000016c8628e675d in acism_lookup (psp=<optimized out>, text=<optimized out>, len=<optimized out>, cb=0x16c59fef58b0 <rspamd_multipattern_acism_cb>, context=0x7f7ffffbda00, statep=0x7f7ffffbda34,
    caseless=true) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/contrib/aho-corasick/acism.c:89
#5  0x000016c59fef5ac6 in rspamd_multipattern_lookup (mp=<optimized out>,
    in=0x16c84cd59000 "@media all and (max-width:590px) {*.responsive {width: 290px !important;}*#center {width: 50%;margin: 0 auto;display: table;}*.responsive-spacer table {width: 20px !important;}ulian Zelizer is a profe"..., len=140187732268576, cb=<optimized out>, ud=<optimized out>, pnfound=0x0) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libutil/multipattern.c:693
#6  0x000016c59fec6f24 in rspamd_url_find_multiple (pool=0x16c897116aa0,
    in=0x16c84cd59000 "@media all and (max-width:590px) {*.responsive {width: 290px !important;}*#center {width: 50%;margin: 0 auto;display: table;}*.responsive-spacer table {width: 20px !important;}ulian Zelizer is a profe"..., inlen=9071, is_html=0, nlines=0x16c7f4b6eb20, func=0x16c59fec7f70 <rspamd_url_text_part_callback>, ud=0x7f7ffffbdb30) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libserver/url.c:2418
#7  0x000016c59fec7488 in rspamd_url_text_extract (pool=<optimized out>, task=0x16c81864c880, part=0x16c809516530, is_html=1289069270) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libserver/url.c:2383
#8  0x000016c59fed98b9 in process_text_part (is_empty=<optimized out>, parent=0x16c84dead030, mime_part=<optimized out>, type=<optimized out>, part_content=<optimized out>, task=<optimized out>)
    at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libmime/message.c:1034
#9  mime_foreach_callback (parent=<optimized out>, part=<optimized out>, user_data=<optimized out>) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libmime/message.c:1236
#10 0x000016c7e373e0a7 in multipart_foreach () from /usr/local/lib/libgmime-2.6.so.0.1
#11 0x000016c59fed7d60 in rspamd_message_parse (task=0x16c81864c880) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libmime/message.c:1512
#12 0x000016c59fec4605 in rspamd_task_process (task=0x16c81864c880, stages=15591) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libserver/task.c:579
#13 0x000016c59fec4652 in rspamd_task_process (task=0x16c81864c880, stages=15591) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libserver/task.c:688
#14 0x000016c59fec4652 in rspamd_task_process (task=0x16c81864c880, stages=15591) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libserver/task.c:688
#15 0x000016c59fe3c573 in rspamd_controller_handle_learn_common (conn_ent=0x16c7f4b6e150, msg=0x16c7b422b0d0, is_spam=1) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/controller.c:1542
#16 0x000016c59fe6f83e in rspamd_http_router_finish_handler (conn=<optimized out>, msg=0x16c7b422b0d0) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libutil/http.c:2940
#17 0x000016c59fe6d4cb in rspamd_http_on_message_complete (parser=<optimized out>) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libutil/http.c:908
#18 0x000016c59ff413d3 in http_parser_execute (parser=0x16c83ce6b810, settings=0x16c83ce6b830,
    data=0x16c8672a3fc9 "\t<tr>\n\n\n", '\t' <repeats 18 times>, "<td>\n\n\n", '\t' <repeats 18 times>, "<div style=\"height:10px;font-size:10px;line-height:10px\">&nbsp;</div>\n\n\n", '\t' <repeats 18 times>, "</td>\n\n\n", '\t' <repeats 17 times>, "</tr>\n\n\n", '\t' <repeats 16 times>, "</tbody>\n\n"..., len=1043) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/contrib/http-parser/http_parser.c:1772
#19 0x000016c59fe6d1ba in rspamd_http_event_handler (fd=<optimized out>, what=<optimized out>, ud=0x16c88a33c1e0) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libutil/http.c:1121
#20 0x000016c805781898 in event_process_active (base=<optimized out>) at /usr/src/lib/libevent/event.c:350
#21 event_base_loop (base=0x16c897116c00, flags=<optimized out>) at /usr/src/lib/libevent/event.c:502
#22 0x000016c59fe39e2b in start_controller_worker (worker=0x16c83a7ccc00) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/controller.c:2844
#23 0x000016c59fec8c3f in rspamd_fork_worker (rspamd_main=0x16c7b283b980, cf=0x16c7c17d7b00, index=<optimized out>, ev_base=0x16c897116000)
    at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/libserver/worker_util.c:596
#24 0x000016c59fe441ca in rspamd_fork_delayed_cb (signo=<optimized out>, what=<optimized out>, arg=0x16c897115830) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/rspamd.c:318
#25 0x000016c805781898 in event_process_active (base=<optimized out>) at /usr/src/lib/libevent/event.c:350
#26 event_base_loop (base=0x16c897116000, flags=<optimized out>) at /usr/src/lib/libevent/event.c:502
#27 0x000016c59fe44e4b in main (argc=1, argv=0x7f7ffffbe9b8, env=<optimized out>) at /usr/ports/pobj/rspamd-1.3.5/rspamd-1.3.5/src/rspamd.c:1347
(gdb) list
1926                            return FALSE;
1927                    }
1928            }
1929
1930            if (pos > cb->begin - 1) {
1931                    match->st = *(pos - 1);
1932            }
1933            else {
1934                    match->st = '\0';
1935            }
(gdb) p *pos
$1 = 64 '@'
(gdb) p *(pos - 1)
Cannot access memory at address 0x16c84cd58fff

```
