### ISSUE TITLE
crash while returning error

### ISSUE THREAD

**Issue by wvolz** [vstakhov/rspamd#970]
I'm seeing numerous crashes with rspamd and am trying to gather information. Here is one that appears to be related to passing a NULL to strlen (maybe)?

```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `rspamd: controller process                   '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
106     ../sysdeps/x86_64/strlen.S: No such file or directory.
(gdb) bt full
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
No locals.
#1  0x000000000047368e in rspamd_vprintf_common ()
No symbol table info available.
#2  0x00000000004c5e51 in rspamd_controller_send_error ()
No symbol table info available.
#3  0x00000000004386fc in ?? ()
No symbol table info available.
#4  0x00000000004afe24 in rspamd_session_pending ()
No symbol table info available.
#5  0x000000000043a85d in ?? ()
No symbol table info available.
#6  0x000000000046bf45 in ?? ()
No symbol table info available.
#7  0x000000000046a091 in ?? ()
No symbol table info available.
#8  0x000000000090097c in http_parser_execute ()
No symbol table info available.
#9  0x000000000046b811 in ?? ()
No symbol table info available.
#10 0x00007f05d5ede3dc in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
No symbol table info available.
#11 0x000000000043bfcf in start_controller_worker ()
No symbol table info available.
#12 0x00000000004c632d in rspamd_fork_worker ()
No symbol table info available.
#13 0x0000000000441766 in ?? ()
No symbol table info available.
#14 0x00007f05d5ede3dc in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
No symbol table info available.
#15 0x00000000004371f7 in main ()
No symbol table info available.
```

**Comment by wvolz** [comment]
I've been unable to reproduce this problem after the fix committed in ce2f800 so I believe this is resolved.
